--------------------------------------------------------------
-- MySQL conversion script for OWL 20.2-owl6.1 to 22.3-owl1 --
--------------------------------------------------------------

----------------------- Begin 20.2 -> 20.3 ---------------------

-- START SAK-42371
ALTER TABLE rbc_evaluation ADD COLUMN status int(11) NOT NULL;
UPDATE rbc_evaluation SET status = 2;
-- END SAK-42371

-- SAK-44810 - Add $Resource.id.history
-- This needs to rename a column in the DB because of a bug that keeps "settings"
-- from working as needed for this feature.
-- MySQL >= 8.0
-- ALTER TABLE lti_tools RENAME COLUMN allowsettings TO allowsettings_ext;
-- MySQL <= 8.0
ALTER TABLE lti_tools CHANGE allowsettings allowsettings_ext TINYINT DEFAULT 0;
-- If autoDDL somehow already ran and created allowsettings_ext - then you need
-- to copy data from the old column and delete it
-- UPDATE lti_tools SET allowsettings_ext=allowsettings;
-- ALTER TABLE lti_tools DROP COLUMN allowsettings;
-- END SAK-44810

-- SAK-41502
-- OWL already has this column
-- ALTER TABLE GB_GRADING_EVENT_T ADD IS_EXCLUDED INT NOT NULL DEFAULT 0;
-- END SAK-41502

------------------------ End 20.2 -> 20.3 ---------------------------

----------- No MySQL database changes for 20.4, 20.5, or 20.6 -------

------------------------ Begin 21.0 ---------------------------------

-- clear unchanged bundle properties
DELETE SAKAI_MESSAGE_BUNDLE from SAKAI_MESSAGE_BUNDLE where PROP_VALUE is NULL;

-- SAK-30079
ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY COLUMN AUTO_FORWARD INT NOT NULL DEFAULT 2;

-- SAK-43826 : Rubrics: Support weighted criterions

ALTER TABLE rbc_rubric ADD weighted BIT NOT NULL;
ALTER TABLE rbc_criterion ADD weight FLOAT DEFAULT 0 NULL;

-- SAK-44637 - Make the Lessons Placement checkbox work
-- Note that SAK-44636 already added the column in sakai_20_1-20_2_mysql_conversion.sql
-- It is included here and commented out in case you need it.
-- ALTER TABLE lti_tools ADD pl_lessonsselection TINYINT DEFAULT 0;
-- Existing records needed to be switched on right before the feature is used
UPDATE lti_tools SET pl_lessonsselection = 1;
-- END SAK-44637

-- SAK-45174 Rubrics metadata datetime conversion
ALTER TABLE rbc_criterion DROP created;
ALTER TABLE rbc_criterion DROP modified;
ALTER TABLE rbc_evaluation DROP created;
ALTER TABLE rbc_evaluation DROP modified;
ALTER TABLE rbc_rating DROP created;
ALTER TABLE rbc_rating DROP modified;
ALTER TABLE rbc_rubric DROP created;
ALTER TABLE rbc_rubric DROP modified;
ALTER TABLE rbc_tool_item_rbc_assoc DROP created;
ALTER TABLE rbc_tool_item_rbc_assoc DROP modified;

ALTER TABLE rbc_criterion ADD created DATETIME NULL;
ALTER TABLE rbc_criterion ADD modified DATETIME NULL;
ALTER TABLE rbc_evaluation ADD created DATETIME NULL;
ALTER TABLE rbc_evaluation ADD modified DATETIME NULL;
ALTER TABLE rbc_rating ADD created DATETIME NULL;
ALTER TABLE rbc_rating ADD modified DATETIME NULL;
ALTER TABLE rbc_rubric ADD created DATETIME NULL;
ALTER TABLE rbc_rubric ADD modified DATETIME NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD created DATETIME NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD modified DATETIME NULL;

UPDATE rbc_criterion SET created = NOW() WHERE created IS NULL;
UPDATE rbc_criterion SET modified = NOW() WHERE modified IS NULL;
UPDATE rbc_evaluation SET created = NOW() WHERE created IS NULL;
UPDATE rbc_evaluation SET modified = NOW() WHERE modified IS NULL;
UPDATE rbc_rating SET created = NOW() WHERE created IS NULL;
UPDATE rbc_rating SET modified = NOW() WHERE modified IS NULL;
UPDATE rbc_rubric SET created = NOW() WHERE created IS NULL;
UPDATE rbc_rubric SET modified = NOW() WHERE modified IS NULL;
UPDATE rbc_tool_item_rbc_assoc SET created = NOW() WHERE created IS NULL;
UPDATE rbc_tool_item_rbc_assoc SET modified = NOW() WHERE modified IS NULL;
-- END SAK-45174

-- SAK-44019
ALTER TABLE ASN_ASSIGNMENT ADD CONTENT_ID INT DEFAULT null NULL;
ALTER TABLE ASN_ASSIGNMENT ADD CONTENT_LAUNCH_NEW_WINDOW BIT DEFAULT 0 NULL;
-- END SAK-44019

-- SAK-45184
CREATE TABLE FILE_CONVERSION_QUEUE (
    ID                   BIGINT       AUTO_INCREMENT PRIMARY KEY,
    ATTEMPTS             INT          NOT NULL,
    LAST_ATTEMPT_STARTED DATETIME     NULL,
    REFERENCE            VARCHAR(255) NOT NULL,
    STATUS               VARCHAR(16)  NOT NULL
);

CREATE INDEX IDX_FCI_REF_TYPE ON FILE_CONVERSION_QUEUE (REFERENCE);

create table MFR_DRAFT_RECIPIENT_T (
    ID           BIGINT           AUTO_INCREMENT PRIMARY KEY,
    BCC          BIT DEFAULT B'0' NOT NULL,
    DRAFT_ID     BIGINT           NOT NULL,
    RECIPIENT_ID VARCHAR(255)     NOT NULL,
    TYPE         INT              NOT NULL
);

CREATE INDEX MFR_DRAFT_REC_MSG_ID_I ON MFR_DRAFT_RECIPIENT_T (DRAFT_ID);

create table TASKS (
    ID          BIGINT       AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DUE         DATETIME     NULL,
    REFERENCE   VARCHAR(255) NOT NULL,
    SITE_ID     VARCHAR(99)  NULL,
    STARTS      DATETIME     NULL,
    SYSTEM      BIT          NOT NULL
);

CREATE INDEX IDX_TASKS_REF_TYPE ON TASKS (REFERENCE);

create table USER_TASKS (
    ID           BIGINT      AUTO_INCREMENT PRIMARY KEY,
    COMPLETE     BIT         NULL,
    NOTES        LONGTEXT    NULL,
    PRIORITY     INT         NOT NULL,
    SOFT_DELETED BIT         NULL,
    USER_ID      VARCHAR(99) NOT NULL,
    TASK_ID      BIGINT      NOT NULL,
    CONSTRAINT FKmj3lsh7wx4o7s7i6hy80tbpsn FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID)
);

CREATE INDEX IDX_USER_TASK ON USER_TASKS (USER_ID, TASK_ID);

ALTER TABLE rbc_tool_item_rbc_assoc ADD active BIT NOT NULL DEFAULT 1;

ALTER TABLE rbc_tool_item_rbc_assoc DROP KEY UK_q4btc0dfymi80bb5mp3vp3r7u;

CREATE INDEX FK1yhjvx9pxp5e76ijo0s6ahvsa ON rbc_tool_item_rbc_assoc(rubric_id);

ALTER TABLE rbc_tool_item_rbc_assoc DROP KEY UKq4btc0dfymi80bb5mp3vp3r7u;

DROP INDEX contentreview_provider_id_idx ON CONTENTREVIEW_ITEM;

CREATE INDEX contentreview_provider_id_idx ON CONTENTREVIEW_ITEM(EXTERNALID);

-- LTI
ALTER TABLE lti_content ADD `description` MEDIUMTEXT NULL;
ALTER TABLE lti_content ADD protect TINYINT DEFAULT 0 NULL;
ALTER TABLE lti_content DROP COLUMN sha256;
ALTER TABLE lti_tools ADD pl_privacy TINYINT DEFAULT 0 NULL;
ALTER TABLE lti_tools ADD pl_coursenav TINYINT DEFAULT 0 NULL;
ALTER TABLE lti_tools ADD lti13_auto_token VARCHAR(1024) NULL;
ALTER TABLE lti_tools ADD lti13_auto_state INT DEFAULT null NULL;
ALTER TABLE lti_tools ADD lti13_auto_registration MEDIUMTEXT NULL;
ALTER TABLE lti_tools MODIFY lti13_tool_keyset VARCHAR(1024);
ALTER TABLE lti_tools DROP COLUMN lti13_tool_kid;
ALTER TABLE lti_tools DROP COLUMN lti13_tool_private;
ALTER TABLE lti_tools DROP COLUMN lti13_tool_public;
ALTER TABLE lti_tools DROP COLUMN sha256;


ALTER TABLE SAKAI_PERSON_T MODIFY PHONETIC_PRONUNCIATION VARCHAR(255);

ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY AUTO_FORWARD INT;
ALTER TABLE MFR_PRIVATE_FORUM_T ALTER AUTO_FORWARD SET DEFAULT null;
DROP INDEX MFR_UNREAD_STATUS_I1 ON MFR_UNREAD_STATUS_T;
CREATE INDEX MFR_UNREAD_STATUS_I1 ON MFR_UNREAD_STATUS_T(TOPIC_C);

-- Polls
ALTER TABLE POLL_OPTION MODIFY DELETED BIT(1) NOT NULL;
ALTER TABLE POLL_OPTION ALTER DELETED SET DEFAULT 0;
-- OWL: this line will fail because we have nulls in option_order, moving to step 2 --
-- ALTER TABLE POLL_OPTION MODIFY OPTION_ORDER INT NOT NULL;
ALTER TABLE POLL_OPTION ALTER OPTION_ORDER DROP DEFAULT;
ALTER TABLE POLL_OPTION MODIFY OPTION_POLL_ID BIGINT NOT NULL;
ALTER TABLE POLL_OPTION ALTER OPTION_POLL_ID DROP DEFAULT;
ALTER TABLE POLL_OPTION MODIFY OPTION_TEXT LONGTEXT NOT NULL;
ALTER TABLE POLL_OPTION MODIFY OPTION_UUID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_OPTION ALTER OPTION_UUID DROP DEFAULT;

update poll_poll set poll_creation_date = poll_vote_open where poll_creation_date is null;
ALTER TABLE POLL_POLL MODIFY POLL_CREATION_DATE datetime NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_CREATION_DATE DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_DISPLAY_RESULT VARCHAR(255) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_DISPLAY_RESULT DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_IS_PUBLIC BIT(1) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_IS_PUBLIC DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_LIMIT_VOTE BIT(1) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_LIMIT_VOTE DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_MAX_OPTIONS INT NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_MAX_OPTIONS DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_MIN_OPTIONS INT NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_MIN_OPTIONS DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_OWNER VARCHAR(255) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_OWNER DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_SITE_ID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_SITE_ID DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_TEXT LONGTEXT NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_UUID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_UUID DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_VOTE_CLOSE datetime NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_VOTE_CLOSE DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_VOTE_OPEN datetime NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_VOTE_OPEN DROP DEFAULT;

ALTER TABLE POLL_VOTE MODIFY VOTE_DATE datetime NOT NULL;
ALTER TABLE POLL_VOTE ALTER VOTE_DATE DROP DEFAULT;
ALTER TABLE POLL_VOTE MODIFY VOTE_IP VARCHAR(255) NOT NULL;
ALTER TABLE POLL_VOTE ALTER VOTE_IP DROP DEFAULT;
ALTER TABLE POLL_VOTE MODIFY VOTE_POLL_ID BIGINT NOT NULL;
ALTER TABLE POLL_VOTE ALTER VOTE_POLL_ID DROP DEFAULT;
ALTER TABLE POLL_VOTE MODIFY VOTE_SUBMISSION_ID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_VOTE ALTER VOTE_SUBMISSION_ID DROP DEFAULT;
ALTER TABLE POLL_VOTE MODIFY USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_VOTE ALTER USER_ID DROP DEFAULT;


-- Site Setup Questions
ALTER TABLE SSQ_ANSWER MODIFY ANSWER VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_ANSWER ALTER ANSWER DROP DEFAULT;
ALTER TABLE SSQ_ANSWER MODIFY FILL_IN_BLANK BIT(1) NOT NULL;
ALTER TABLE SSQ_ANSWER ALTER FILL_IN_BLANK DROP DEFAULT;
ALTER TABLE SSQ_ANSWER MODIFY ORDER_NUM INT NOT NULL;
ALTER TABLE SSQ_ANSWER ALTER ORDER_NUM DROP DEFAULT;

ALTER TABLE SSQ_QUESTION MODIFY IS_CURRENT VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_QUESTION ALTER IS_CURRENT DROP DEFAULT;
ALTER TABLE SSQ_QUESTION MODIFY MULTIPLE_ANSWERS BIT(1) NOT NULL;
ALTER TABLE SSQ_QUESTION ALTER MULTIPLE_ANSWERS DROP DEFAULT;
ALTER TABLE SSQ_QUESTION MODIFY ORDER_NUM INT NOT NULL;
ALTER TABLE SSQ_QUESTION ALTER ORDER_NUM DROP DEFAULT;
ALTER TABLE SSQ_QUESTION MODIFY REQUIRED BIT(1) NOT NULL;
ALTER TABLE SSQ_QUESTION ALTER REQUIRED DROP DEFAULT;

ALTER TABLE SSQ_USER_ANSWER MODIFY SITE_ID VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_USER_ANSWER ALTER SITE_ID DROP DEFAULT;
ALTER TABLE SSQ_USER_ANSWER MODIFY USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_USER_ANSWER ALTER USER_ID DROP DEFAULT;

ALTER TABLE SSQ_SITETYPE_QUESTIONS MODIFY SITE_TYPE VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_SITETYPE_QUESTIONS ALTER SITE_TYPE DROP DEFAULT;

-- END SAK-45184

------------------------ End 21.0 -----------------------------------

---------------------- Begin 21.0 -> 21.1 ---------------------------

-- START SAK-45137
UPDATE rbc_rating SET title = '' WHERE title IS NULL;
ALTER TABLE rbc_rating MODIFY title VARCHAR(255) NOT NULL;
ALTER TABLE rbc_rating ALTER title DROP DEFAULT;

UPDATE rbc_rating SET points = 0 WHERE points IS NULL;
ALTER TABLE rbc_rating MODIFY points DOUBLE NOT NULL;
ALTER TABLE rbc_rating ALTER points DROP DEFAULT;
-- END SAK-45137

-- START SAK-45601
CREATE TABLE TINCANAPI_EVENT (
EVENT VARCHAR(32) NOT NULL,
VERB VARCHAR(64) NOT NULL,
ORIGIN VARCHAR(64) NOT NULL,
OBJECT VARCHAR(64) NOT NULL,
EVENT_SUPPLIER VARCHAR(64),
PRIMARY KEY (EVENT));

-- Initial data that were in the ifs:
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('user.login', 'initialized', 'sakai.system', 'session-started', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('user.login.container', 'initialized', 'sakai.system', 'session-started', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('user.logout', 'exited', 'sakai.system', 'session-ended', 'logout');
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('annc.read', 'experienced', 'announcement', 'view-announcement', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('calendar.read', 'experienced', 'calendar', 'view-calendar', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('chat.new', 'responded', 'chat', 'view-chats', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('chat.read', 'experienced', 'chat', 'view-chats', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('content.read', 'interacted', 'sakai.resources', 'view-resource', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('content.new', 'shared', 'sakai.resources', 'add-resource', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('content.revise', 'shared', 'sakai.resources', 'edit-resource', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('gradebook.read', 'experienced', 'gradebook', 'view-grades', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('lessonbuilder.page.read', 'experienced', 'lessonbuilder', 'view-lesson', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('lessonbuilder.item.read', 'experienced', 'lessonbuilder', 'view-lesson', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('news.read', 'experienced', 'news', 'view-news', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('podcast.read', 'experienced', 'podcast', 'view-podcast', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('podcast.read.public', 'experienced', 'podcast', 'view-podcast', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('podcast.read.site', 'experienced', 'podcast', 'view-podcast', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('syllabus.read', 'experienced', 'syllabus', 'view-syllabus', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('webcontent.read', 'experienced', 'webcontent', 'view-web-content', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('wiki.new', 'initialized', 'rwiki', 'add-wiki-page', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('wiki.revise', 'shared', 'rwiki', 'edit-wiki-page', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('wiki.read', 'experienced', 'rwiki', 'view-wiki-page', null);
-- END SAK-45601

-- START SAK-45575
CREATE INDEX IDX_FCI_STATUS ON FILE_CONVERSION_QUEUE(STATUS);
-- END SAK-45575

-- START SAK-45580
DROP INDEX IDX_FCI_REF_TYPE ON FILE_CONVERSION_QUEUE;
-- END SAK-45580

---------------------- End 21.0 -> 21.1 -----------------------------

-------------------- Begin 21.1 -> 21.2 -----------------------------

-- SAK-45435
ALTER TABLE lti_tools ADD     lti13_platform_public_old MEDIUMTEXT NULL;
ALTER TABLE lti_tools ADD     lti13_platform_public_old_at DATETIME NULL;
-- End SAK-45435

-- SAK-43510
ALTER TABLE SAKAI_PERSON_T ADD PRONOUNS varchar(255);
-- End SAK-43510

-- SAK-45491
ALTER TABLE lti_tools ADD lti13_platform_public_next MEDIUMTEXT;
ALTER TABLE lti_tools ADD lti13_platform_public_next_at DATETIME NULL;
ALTER TABLE lti_tools ADD lti13_platform_private_next MEDIUMTEXT;
-- End SAK-45491

-- Start SAK-45692
ALTER TABLE FILE_CONVERSION_QUEUE ADD CONSTRAINT UK_j0t1gd58buw5b0cwxayincy09 UNIQUE (`REFERENCE`);
-- End SAK-45692

------- OWL: Snippet below commented out, it will break access to certain uploaded files. See OWL-5293 ----------
-- Start SAK-46414
-- ALTER TABLE SAM_MEDIA_T DROP COLUMN ISHTMLINLINE;
-- ALTER TABLE SAM_MEDIA_T DROP COLUMN MEDIA;
-- End SAK-46414

---------------------- End 21.1 -> 21.2 -----------------------------

------------------- Begin 21.2 -> 21.3 ------------------------------

-- Start SAK-41604
ALTER TABLE RBC_EVALUATION ADD COLUMN EVALUATED_ITEM_OWNER_TYPE INT;
-- End SAK-41604

-- SAK-45987
CREATE TABLE rbc_returned_criterion_out (
  id BIGINT AUTO_INCREMENT NOT NULL,
  comments LONGTEXT NULL,
  criterion_id BIGINT DEFAULT NULL NULL,
  points DOUBLE DEFAULT NULL NULL,
  pointsAdjusted BIT NOT NULL,
  selected_rating_id BIGINT DEFAULT NULL NULL,
  CONSTRAINT PK_RBC_RETURNED_CRITERION_OUT PRIMARY KEY (id)
);

CREATE TABLE rbc_returned_criterion_outs (
  rbc_returned_evaluation_id BIGINT NOT NULL,
  rbc_returned_criterion_out_id BIGINT NOT NULL,
  UNIQUE (rbc_returned_criterion_out_id)
);

CREATE TABLE rbc_returned_evaluation (
  id BIGINT AUTO_INCREMENT NOT NULL,
  original_evaluation_id BIGINT NOT NULL,
  overallComment VARCHAR(255) NULL,
  CONSTRAINT PK_RBC_RETURNED_EVALUATION PRIMARY KEY (id)
);

CREATE INDEX FK3sroha5yjh3cbvq0on02wf3fk ON rbc_returned_criterion_out(criterion_id);
CREATE INDEX rbc_ret_orig_id ON rbc_returned_evaluation(original_evaluation_id);
CREATE INDEX returned_evaluation_id_key ON rbc_returned_criterion_outs(rbc_returned_evaluation_id);

ALTER TABLE rbc_returned_criterion_out ADD CONSTRAINT FK3sroha5yjh3cbvq0on02wf3fk FOREIGN KEY (criterion_id) REFERENCES rbc_criterion (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE rbc_returned_criterion_outs ADD CONSTRAINT returned_criterion_out_id_fk FOREIGN KEY (rbc_returned_criterion_out_id) REFERENCES rbc_returned_criterion_out (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE rbc_returned_criterion_outs ADD CONSTRAINT returned_evalution_id_fk FOREIGN KEY (rbc_returned_evaluation_id) REFERENCES rbc_returned_evaluation (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- END SAK-45987

-- SAK-46977

-- Add the new function
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('sitestats.all');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('sitestats.own');

-- Backfil permission
CREATE TABLE PERMISSIONS_SRC_TEMP (ROLE_NAME VARCHAR(99), FUNCTION_NAME VARCHAR(99));

INSERT INTO PERMISSIONS_SRC_TEMP VALUES('maintain','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Instructor','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Content Designer','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Course Coordinator','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Grade Admin','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Librarian','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Secondary Instructor','sitestats.all');
-- OWL: we will not be granting students the 'sitestats.own' permission
-- INSERT INTO PERMISSIONS_SRC_TEMP VALUES('access','sitestats.own');
-- INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Student','sitestats.own');

-- lookup the role and function number
CREATE TABLE PERMISSIONS_TEMP (ROLE_KEY INTEGER, FUNCTION_KEY INTEGER);
INSERT INTO PERMISSIONS_TEMP (ROLE_KEY, FUNCTION_KEY)
SELECT SRR.ROLE_KEY, SRF.FUNCTION_KEY
FROM PERMISSIONS_SRC_TEMP TMPSRC
JOIN SAKAI_REALM_ROLE SRR ON (TMPSRC.ROLE_NAME = SRR.ROLE_NAME)
JOIN SAKAI_REALM_FUNCTION SRF ON (TMPSRC.FUNCTION_NAME = SRF.FUNCTION_NAME);

-- insert the new function into the roles of any existing realm that has the role (don't convert the "!site.helper")
INSERT INTO SAKAI_REALM_RL_FN (REALM_KEY, ROLE_KEY, FUNCTION_KEY)
SELECT
    SRRFD.REALM_KEY, SRRFD.ROLE_KEY, TMP.FUNCTION_KEY
FROM
    (SELECT DISTINCT SRRF.REALM_KEY, SRRF.ROLE_KEY FROM SAKAI_REALM_RL_FN SRRF) SRRFD
    JOIN PERMISSIONS_TEMP TMP ON (SRRFD.ROLE_KEY = TMP.ROLE_KEY)
    JOIN SAKAI_REALM SR ON (SRRFD.REALM_KEY = SR.REALM_KEY)
    WHERE SR.REALM_ID != '!site.helper'
    AND NOT EXISTS (
        SELECT 1
            FROM SAKAI_REALM_RL_FN SRRFI
            WHERE SRRFI.REALM_KEY=SRRFD.REALM_KEY AND SRRFI.ROLE_KEY=SRRFD.ROLE_KEY AND SRRFI.FUNCTION_KEY=TMP.FUNCTION_KEY
    );

-- clean up the temp tables
DROP TABLE PERMISSIONS_TEMP;
DROP TABLE PERMISSIONS_SRC_TEMP;

-- END SAK-46977

---------------------- End 21.2 -> 21.3 -----------------------------

-------------------- Begin 21.3 -> 21.4 -----------------------------

-- SAK-45330
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('rubrics.manager.view');

CREATE TABLE PERMISSIONS_SRC_TEMP (ROLE_NAME VARCHAR(99), FUNCTION_NAME VARCHAR(99));

INSERT INTO PERMISSIONS_SRC_TEMP VALUES('maintain','rubrics.manager.view');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Instructor','rubrics.manager.view');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Course Coordinator','rubrics.manager.view');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Grade Admin','rubrics.manager.view');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Secondary Instructor','rubrics.manager.view');

CREATE TABLE PERMISSIONS_TEMP (ROLE_KEY INTEGER, FUNCTION_KEY INTEGER);
INSERT INTO PERMISSIONS_TEMP (ROLE_KEY, FUNCTION_KEY)
SELECT SRR.ROLE_KEY, SRF.FUNCTION_KEY
FROM PERMISSIONS_SRC_TEMP TMPSRC
JOIN SAKAI_REALM_ROLE SRR ON (TMPSRC.ROLE_NAME = SRR.ROLE_NAME)
JOIN SAKAI_REALM_FUNCTION SRF ON (TMPSRC.FUNCTION_NAME = SRF.FUNCTION_NAME);

INSERT INTO SAKAI_REALM_RL_FN (REALM_KEY, ROLE_KEY, FUNCTION_KEY)
SELECT
    SRRFD.REALM_KEY, SRRFD.ROLE_KEY, TMP.FUNCTION_KEY
FROM
    (SELECT DISTINCT SRRF.REALM_KEY, SRRF.ROLE_KEY FROM SAKAI_REALM_RL_FN SRRF) SRRFD
    JOIN PERMISSIONS_TEMP TMP ON (SRRFD.ROLE_KEY = TMP.ROLE_KEY)
    JOIN SAKAI_REALM SR ON (SRRFD.REALM_KEY = SR.REALM_KEY)
    WHERE SR.REALM_ID != '!site.helper'
    AND NOT EXISTS (
        SELECT 1
            FROM SAKAI_REALM_RL_FN SRRFI
            WHERE SRRFI.REALM_KEY=SRRFD.REALM_KEY AND SRRFI.ROLE_KEY=SRRFD.ROLE_KEY AND SRRFI.FUNCTION_KEY=TMP.FUNCTION_KEY
    );

-- clean up the temp tables
DROP TABLE PERMISSIONS_TEMP;
DROP TABLE PERMISSIONS_SRC_TEMP;

-- SAK-45330 END

---------------------- End 21.3 -> 21.4 -----------------------------

------------------------- Begin 22.0 --------------------------------

-- SAK-45565
ALTER TABLE lesson_builder_groups CHANGE COLUMN `groups` item_groups LONGTEXT NULL DEFAULT NULL;
ALTER TABLE lesson_builder_items CHANGE COLUMN `groups` item_groups LONGTEXT NULL DEFAULT NULL;
ALTER TABLE tasks CHANGE COLUMN `SYSTEM` SYSTEM_TASK BIT(1) NOT NULL;
-- SAK-45565

-- SAK-44967
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN ALLOW_COMPARE_GRADES BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_FIRSTNAMES BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_SURNAMES BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_COMMENTS BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_ALLITEMS BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_RANDOMIZEDATA BIT(1) DEFAULT FALSE NOT NULL;
-- End SAK-44967

-- Conversations
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.anonymous.view');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.comment.create');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.comment.delete.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.comment.delete.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.comment.update.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.comment.update.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.moderate');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.post.create');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.post.delete.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.post.delete.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.post.react');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.post.update.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.post.update.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.post.upvote');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.roletype.instructor');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.statistics.view');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.tag.create');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.topic.create');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.topic.delete.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.topic.delete.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.topic.pin');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.topic.tag');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.topic.update.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.topic.update.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES('conversations.topic.view.groups');

-- OWL: we are not enabling this tool so will not backfill permissions --

-- End Conversations

-- SAK-46022
ALTER TABLE COMMONS_POST ADD COLUMN PRIORITY BIT(1) DEFAULT 0 NOT NULL;
-- End SAK-46022

-- SAK-43155
ALTER TABLE ASN_ASSIGNMENT ADD ESTIMATE_REQUIRED BIT(1) DEFAULT 0 NOT NULL;
ALTER TABLE ASN_ASSIGNMENT ADD ESTIMATE VARCHAR(255) NULL;
-- End SAK-43155

-- SAK-46021
CREATE TABLE COMMONS_LIKE (
USER_ID VARCHAR(99) NOT NULL,
POST_ID CHAR(36) NOT NULL,
VOTE bit(1) DEFAULT 0 NOT NULL,
MODIFIED_DATE datetime,
PRIMARY KEY (USER_ID, POST_ID)
);
-- End SAK-46021

-- SAK-46137
ALTER TABLE SAKAI_PERSON_T ADD PRINCIPAL_NAME_PRIOR varchar(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD SCOPED_AFFILIATION varchar(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD TARGETED_ID varchar(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD ASSURANCE varchar(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD UNIQUE_ID varchar(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD ORCID varchar(255) DEFAULT NULL;
-- End SAK-46137

-- SAK-46085
ALTER TABLE PROFILE_SOCIAL_INFO_T ADD COLUMN INSTAGRAM_URL VARCHAR(255) NULL;
-- End SAK-46085

-- SAK-45092
CREATE TABLE CONV_COMMENTS (
  COMMENT_ID VARCHAR(36) NOT NULL,
  `LOCKED` BIT DEFAULT 0 NULL,
  MESSAGE VARCHAR(255) NOT NULL,
  CREATED datetime NOT NULL,
  CREATOR VARCHAR(99) NULL,
  MODIFIED datetime DEFAULT NULL NULL,
  MODIFIER VARCHAR(99) NULL,
  SITE_ID VARCHAR(99) NOT NULL,
  POST_ID VARCHAR(36) NOT NULL,
  CONSTRAINT PK_CONV_COMMENTS PRIMARY KEY (COMMENT_ID)
);

CREATE TABLE CONV_POSTS (
  POST_ID VARCHAR(36) NOT NULL,
  ANONYMOUS BIT DEFAULT 0 NULL,
  DRAFT BIT DEFAULT 0 NULL,
  HIDDEN BIT DEFAULT 0 NULL,
  `LOCKED` BIT DEFAULT 0 NULL,
  MESSAGE LONGTEXT NOT NULL,
  CREATED datetime NOT NULL,
  CREATOR VARCHAR(99) NULL,
  MODIFIED datetime DEFAULT NULL NULL,
  MODIFIER VARCHAR(99) NULL,
  NUMBER_OF_COMMENTS INT DEFAULT NULL NULL,
  PRIVATE_POST BIT DEFAULT 0 NULL,
  SITE_ID VARCHAR(99) NOT NULL,
  UPVOTES INT DEFAULT NULL NULL,
  PARENT_POST_ID VARCHAR(36) NULL,
  TOPIC_ID VARCHAR(36) NOT NULL,
  CONSTRAINT PK_CONV_POSTS PRIMARY KEY (POST_ID)
);

CREATE TABLE CONV_POST_REACTIONS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  REACTION INT NOT NULL,
  REACTION_STATE BIT DEFAULT 0 NULL,
  USER_ID VARCHAR(99) NOT NULL,
  POST_ID VARCHAR(36) NOT NULL,
  CONSTRAINT PK_CONV_POST_REACTIONS PRIMARY KEY (ID)
);

CREATE TABLE CONV_POST_REACTION_TOTALS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  REACTION INT NOT NULL,
  TOTAL INT NOT NULL,
  POST_ID VARCHAR(36) NOT NULL,
  CONSTRAINT PK_CONV_POST_REACTION_TOTALS PRIMARY KEY (ID)
);

CREATE TABLE CONV_POST_STATUS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  POST_ID VARCHAR(255) NOT NULL,
  TOPIC_ID VARCHAR(255) NOT NULL,
  UPVOTED BIT DEFAULT 0 NULL,
  USER_ID VARCHAR(99) NOT NULL,
  VIEWED BIT DEFAULT 0 NULL,
  VIEWED_DATE datetime DEFAULT NULL NULL,
  CONSTRAINT PK_CONV_POST_STATUS PRIMARY KEY (ID)
);

CREATE TABLE CONV_SETTINGS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  ALLOW_ANON_POSTING BIT DEFAULT 0 NULL,
  ALLOW_BOOKMARKING BIT DEFAULT 0 NULL,
  ALLOW_PINNING BIT DEFAULT 0 NULL,
  ALLOW_REACTIONS BIT DEFAULT 0 NULL,
  ALLOW_UPVOTING BIT DEFAULT 0 NULL,
  DEFAULT_TOPIC_TYPE VARCHAR(32) NULL,
  GUIDELINES LONGTEXT NULL,
  REQUIRE_GUIDELINES_AGREEMENT BIT DEFAULT 0 NULL,
  SITE_ID VARCHAR(99) NOT NULL,
  SITE_LOCKED BIT DEFAULT 0 NULL,
  CONSTRAINT PK_CONV_SETTINGS PRIMARY KEY (ID),
  UNIQUE (SITE_ID)
);

CREATE TABLE CONV_STATUS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  GUIDELINES_AGREED BIT DEFAULT 0 NULL,
  SITE_ID VARCHAR(99) NOT NULL,
  USER_ID VARCHAR(99) NOT NULL,
  CONSTRAINT PK_CONV_STATUS PRIMARY KEY (ID)
);

CREATE TABLE CONV_TAGS (
  TAG_ID BIGINT AUTO_INCREMENT NOT NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  LABEL VARCHAR(255) NOT NULL,
  SITE_ID VARCHAR(99) NOT NULL,
  CONSTRAINT PK_CONV_TAGS PRIMARY KEY (TAG_ID)
);

CREATE TABLE CONV_TOPICS (
  TOPIC_ID VARCHAR(36) NOT NULL,
  ABOUT_REFERENCE VARCHAR(255) NULL,
  ALLOW_ANONYMOUS_POSTS BIT DEFAULT 0 NULL,
  ANONYMOUS BIT DEFAULT 0 NULL,
  DRAFT BIT DEFAULT 0 NULL,
  HIDDEN BIT DEFAULT 0 NULL,
  HOW_ACTIVE INT DEFAULT NULL NULL,
  LAST_ACTIVITY datetime DEFAULT NULL NULL,
  `LOCKED` BIT DEFAULT 0 NULL,
  MESSAGE LONGTEXT NULL,
  CREATED datetime NOT NULL,
  CREATOR VARCHAR(99) NULL,
  MODIFIED datetime DEFAULT NULL NULL,
  MODIFIER VARCHAR(99) NULL,
  PINNED BIT DEFAULT 0 NULL,
  RESOLVED BIT DEFAULT 0 NULL,
  SITE_ID VARCHAR(99) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  TOPIC_TYPE VARCHAR(32) NULL,
  VISIBILITY VARCHAR(32) NULL,
  CONSTRAINT PK_CONV_TOPICS PRIMARY KEY (TOPIC_ID)
);

CREATE TABLE CONV_TOPIC_GROUPS (
  TOPIC_ID VARCHAR(36) NOT NULL,
  GROUP_ID VARCHAR(255) NULL
);

CREATE TABLE CONV_TOPIC_REACTIONS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  REACTION INT NOT NULL,
  REACTION_STATE BIT DEFAULT 0 NULL,
  USER_ID VARCHAR(99) NOT NULL,
  TOPIC_ID VARCHAR(36) NOT NULL,
  CONSTRAINT PK_CONV_TOPIC_REACTIONS PRIMARY KEY (ID)
);

CREATE TABLE CONV_TOPIC_REACTION_TOTALS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  REACTION INT NOT NULL,
  TOTAL INT NOT NULL,
  TOPIC_ID VARCHAR(36) NOT NULL,
  CONSTRAINT PK_CONV_TOPIC_REACTION_TOTALS PRIMARY KEY (ID)
);

CREATE TABLE CONV_TOPIC_STATUS (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  BOOKMARKED BIT DEFAULT 0 NULL,
  SITE_ID VARCHAR(255) NOT NULL,
  TOPIC_ID VARCHAR(255) NOT NULL,
  UNREAD INT DEFAULT NULL NULL,
  USER_ID VARCHAR(99) NOT NULL,
  VIEWED BIT DEFAULT 0 NULL,
  CONSTRAINT PK_CONV_TOPIC_STATUS PRIMARY KEY (ID)
);

CREATE TABLE CONV_TOPIC_TAGS (
  TOPIC_ID VARCHAR(36) NOT NULL,
  TAG BIGINT DEFAULT NULL NULL
);

CREATE TABLE CONV_USER_STATISTICS (
  ID BIGINT NOT NULL,
  LAST_POST_DATE datetime DEFAULT NULL NULL,
  NUMBER_OF_POSTS INT DEFAULT NULL NULL,
  NUMBER_OF_REACTIONS INT DEFAULT NULL NULL,
  NUMBER_OF_REPLIES INT DEFAULT NULL NULL,
  NUMBER_OF_UPVOTES INT DEFAULT NULL NULL,
  NUMBER_READ INT DEFAULT NULL NULL,
  USER_ID VARCHAR(99) NOT NULL,
  TOPIC_ID VARCHAR(36) NULL,
  CONSTRAINT PK_CONV_USER_STATISTICS PRIMARY KEY (ID)
);

ALTER TABLE CONV_STATUS ADD CONSTRAINT UniqueConvStatus UNIQUE (SITE_ID, USER_ID);
ALTER TABLE CONV_POST_REACTION_TOTALS ADD CONSTRAINT UniquePostReactionTotals UNIQUE (POST_ID, REACTION);
ALTER TABLE CONV_POST_REACTIONS ADD CONSTRAINT UniquePostReactions UNIQUE (POST_ID, USER_ID, REACTION);
ALTER TABLE CONV_POST_STATUS ADD CONSTRAINT UniquePostStatus UNIQUE (POST_ID, USER_ID);
ALTER TABLE CONV_TOPIC_REACTION_TOTALS ADD CONSTRAINT UniqueTopicReactionTotals UNIQUE (TOPIC_ID, REACTION);
ALTER TABLE CONV_TOPIC_REACTIONS ADD CONSTRAINT UniqueTopicReactions UNIQUE (TOPIC_ID, USER_ID, REACTION);
ALTER TABLE CONV_TOPIC_STATUS ADD CONSTRAINT UniqueTopicStatus UNIQUE (TOPIC_ID, USER_ID);

CREATE INDEX FKc21ukywsqsqilxlsdrg4x6qka ON CONV_POSTS(PARENT_POST_ID);
CREATE INDEX FKi9pfkqq0396p0kl718e9mrakk ON CONV_USER_STATISTICS(TOPIC_ID);
CREATE INDEX FKj8o3cwa4flprmopiaa1xxi91s ON CONV_TOPIC_GROUPS(TOPIC_ID);
CREATE INDEX FKrmek6b1bqs2jghppp27ph2dn9 ON CONV_TOPIC_TAGS(TOPIC_ID);
CREATE INDEX IDX3nridt976wgqrd0vxge273ctk ON CONV_POST_REACTIONS(POST_ID);
CREATE INDEX IDX4vl5kx35nbj7mm5tjc789pkrs ON CONV_POST_STATUS(POST_ID);
CREATE INDEX IDX59e65g24yqkm9d4omljmdk2i9 ON CONV_POSTS(SITE_ID);
CREATE INDEX IDX9tgexj1wml170sorc2agiac1i ON CONV_TAGS(SITE_ID);
CREATE INDEX IDXbb22xsa2tdsm7jv8v0w1rwxvh ON CONV_POST_REACTION_TOTALS(POST_ID);
CREATE INDEX IDXdsq2b214fvqnhxevs6ogx37po ON CONV_POST_REACTIONS(POST_ID, USER_ID);
CREATE INDEX IDXeisyrk9cbbkdmqo5on3e7pysg ON CONV_COMMENTS(SITE_ID);
CREATE INDEX IDXhw1kgsuv0qp47fvc8meopwaea ON CONV_POST_STATUS(TOPIC_ID, USER_ID);
CREATE INDEX IDXih3xad6e7nljy7cw8dsinq5j4 ON CONV_POSTS(TOPIC_ID);
CREATE INDEX IDXjuusvvw52sys4e6fa9bn5rs6t ON CONV_USER_STATISTICS(USER_ID);
CREATE INDEX IDXl2syeorinknc7t5e8jrctam81 ON CONV_POST_STATUS(USER_ID);
CREATE INDEX IDXo21yr7ncf5o3qrtwv36pc083k ON CONV_TOPICS(SITE_ID);
CREATE INDEX IDXp4bavayq4l7jiplafk6swbst ON CONV_TOPIC_REACTION_TOTALS(TOPIC_ID);
CREATE INDEX IDXq3yulh1p20c1eggq63he9mvoh ON CONV_TOPIC_REACTIONS(TOPIC_ID, USER_ID);
CREATE INDEX IDXqu1kvjnw63lom1ymespiiomqm ON CONV_TOPIC_REACTIONS(TOPIC_ID);
CREATE INDEX IDXtf2j5cl6yv4mrhxb06oc4s4hu ON CONV_COMMENTS(POST_ID);

ALTER TABLE CONV_COMMENTS ADD CONSTRAINT FK5ivsmxyitqpbm7pmdnu3lnmyi FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_POSTS ADD CONSTRAINT FKc21ukywsqsqilxlsdrg4x6qka FOREIGN KEY (PARENT_POST_ID) REFERENCES CONV_POSTS (POST_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_USER_STATISTICS ADD CONSTRAINT FKi9pfkqq0396p0kl718e9mrakk FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_POST_REACTION_TOTALS ADD CONSTRAINT FKirwlickqy5sf8o9ejk1qkuit6 FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_TOPIC_GROUPS ADD CONSTRAINT FKj8o3cwa4flprmopiaa1xxi91s FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_TOPIC_REACTIONS ADD CONSTRAINT FKpwv7vrkag66g9kq6gghtc4uy1 FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_POSTS ADD CONSTRAINT FKqaspmpv6ull7whideia5i2cnb FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_TOPIC_REACTION_TOTALS ADD CONSTRAINT FKqu7eyh63vtkowyqoqa9xy7wmq FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_POST_REACTIONS ADD CONSTRAINT FKqv38yghf2km7vq1i717xywih6 FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE CONV_TOPIC_TAGS ADD CONSTRAINT FKrmek6b1bqs2jghppp27ph2dn9 FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- END SAK-45092

-- SAK-46685
CREATE TABLE TIMESHEET_ENTRY (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  TEXT_COMMENT VARCHAR(4000) NULL,
  DURATION VARCHAR(255) NULL,
  `REFERENCE` VARCHAR(255) NOT NULL,
  START_TIME datetime NOT NULL,
  USER_ID VARCHAR(99) NULL,
  CONSTRAINT PK_TIMESHEET_ENTRY PRIMARY KEY (ID)
);

CREATE INDEX IDX_TIMESHEETENTRY_REF_USER ON TIMESHEET_ENTRY(`REFERENCE`, USER_ID);
-- END SAK-46685

-- SAK-43155
ALTER TABLE ASN_SUBMISSION_SUBMITTER ADD TIME_SPENT VARCHAR(255) NULL;
-- END SAK-43155

-- SAK-46686
ALTER TABLE GB_GRADE_RECORD_T ADD ENTERED_POINTS DOUBLE DEFAULT null NULL;
-- END SAK-46686

-- SAK-44784
ALTER TABLE SAKAI_SYLLABUS_ATTACH MODIFY lockId INT NULL;
ALTER TABLE SAKAI_SYLLABUS_ATTACH ALTER lockId SET DEFAULT null;
ALTER TABLE SAKAI_SYLLABUS_DATA MODIFY lockId INT NULL;
ALTER TABLE SAKAI_SYLLABUS_DATA ALTER lockId SET DEFAULT null;
ALTER TABLE SAKAI_SYLLABUS_ITEM MODIFY lockId INT NULL;
ALTER TABLE SAKAI_SYLLABUS_ITEM ALTER lockId SET DEFAULT null;
-- END SAK-44784

-- SAK-45194
ALTER TABLE rbc_evaluation MODIFY status INT NULL;
ALTER TABLE rbc_evaluation ALTER status SET DEFAULT null;
-- END SAK-45194

------------------------- End 22.0 ----------------------------------

------------------- Begin 22.0 -> 22.1 ------------------------------

-- SAK-46436 START
CREATE TABLE TASKS_ASSIGNED
(
    ID               BIGINT AUTO_INCREMENT NOT NULL,
    OBJECT_ID        VARCHAR(99)           NULL,
    ASSIGNATION_TYPE VARCHAR(255)          NOT NULL,
    TASK_ID          BIGINT                NOT NULL,
    CONSTRAINT PK_TASKS_ASSIGNED PRIMARY KEY (ID)
);

ALTER TABLE TASKS ADD TASK_OWNER VARCHAR(99) NULL;
CREATE INDEX IDX_TASKS_ASSIGNED ON TASKS_ASSIGNED (TASK_ID);
ALTER TABLE TASKS_ASSIGNED
    ADD CONSTRAINT FK915ilfdtgcwqab3xuyfwn95ao FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- SAK-46436 END

-- SAK-46986 START
CREATE TABLE TASK_GROUPS
(
    TASK_ID  BIGINT      NOT NULL,
    GROUP_ID VARCHAR(99) NULL
);

CREATE INDEX FK7x7ajup3bwe3hcwq057evmala ON TASK_GROUPS (TASK_ID);
ALTER TABLE TASK_GROUPS
    ADD CONSTRAINT FK7x7ajup3bwe3hcwq057evmala FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- SAK-46986 END

-- SAK-46178 START
ALTER TABLE rbc_rating ADD order_index INT DEFAULT null NULL;
ALTER TABLE rbc_criterion ADD order_index INT DEFAULT null NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD siteId VARCHAR(99) NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD CONSTRAINT rbc_item_rubric UNIQUE (itemId, rubric_id);
ALTER TABLE rbc_criterion_ratings DROP FOREIGN KEY FK2ecdorwm3nm2ytyg9uvxlik53;
ALTER TABLE rbc_criterion_ratings DROP FOREIGN KEY FKd03estm381c26jhsq4wd44vwx;
ALTER TABLE rbc_evaluation DROP FOREIGN KEY FKem9md18gcni93xqa5ijykty8e;
ALTER TABLE rbc_rubric_criterions DROP FOREIGN KEY FKilhg1u02m1765ltp3253wp7hn;
ALTER TABLE rbc_rubric_criterions DROP FOREIGN KEY FKt5dmnek3q7syuqck0uk9rw2hg;
ALTER TABLE rbc_criterion_ratings DROP KEY UK_funjjd0xkrmm5x300r7i4la83;

ALTER TABLE rbc_criterion DROP COLUMN created;
ALTER TABLE rbc_rating DROP COLUMN created;
ALTER TABLE rbc_criterion DROP COLUMN creatorId;
ALTER TABLE rbc_rating DROP COLUMN creatorId;
ALTER TABLE rbc_rubric DROP COLUMN `description`;
ALTER TABLE rbc_criterion DROP COLUMN modified;
ALTER TABLE rbc_rating DROP COLUMN modified;
ALTER TABLE rbc_rating DROP COLUMN ownerId;
ALTER TABLE rbc_criterion DROP COLUMN ownerType;
ALTER TABLE rbc_evaluation DROP COLUMN ownerType;
ALTER TABLE rbc_rating DROP COLUMN ownerType;
ALTER TABLE rbc_rubric DROP COLUMN ownerType;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN ownerType;
ALTER TABLE rbc_criterion DROP COLUMN shared;
ALTER TABLE rbc_evaluation DROP COLUMN shared;
ALTER TABLE rbc_rating DROP COLUMN shared;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN shared;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN ownerId;
ALTER TABLE rbc_criterion_outcome MODIFY pointsAdjusted BIT(1) NULL;
ALTER TABLE rbc_criterion_outcome ALTER pointsAdjusted SET DEFAULT 0;
ALTER TABLE rbc_returned_criterion_out MODIFY pointsAdjusted BIT(1) NULL;
ALTER TABLE rbc_returned_criterion_out ALTER pointsAdjusted SET DEFAULT 0;
ALTER TABLE rbc_rubric MODIFY shared BIT(1) NULL;
ALTER TABLE rbc_rubric ALTER shared SET DEFAULT 0;
ALTER TABLE rbc_criterion ALTER weight SET DEFAULT null;
ALTER TABLE rbc_rubric MODIFY weighted BIT(1) NULL;
ALTER TABLE rbc_rubric ALTER weighted SET DEFAULT 0;
DROP INDEX rbc_tool_item_owner ON rbc_tool_item_rbc_assoc;
CREATE INDEX rbc_tool_item_owner ON rbc_tool_item_rbc_assoc (toolId, itemId, siteId);

-- this migrates the data from the link tables
UPDATE rbc_criterion rc JOIN rbc_rubric_criterions rrc ON rc.id = rrc.criterions_id SET rc.rubric_id = rrc.rbc_rubric_id, rc.order_index = rrc.order_index WHERE rc.rubric_id is NULL OR rc.order_index is NULL;
UPDATE rbc_rating rc JOIN rbc_criterion_ratings rcr ON rc.id = rcr.ratings_id SET rc.criterion_id = rcr.rbc_criterion_id, rc.order_index = rcr.order_index WHERE rc.criterion_id is NULL OR rc.order_index is NULL;
UPDATE rbc_tool_item_rbc_assoc rti JOIN rbc_rubric rc ON rti.rubric_id = rc.id SET rti.siteId = rc.ownerId WHERE rti.siteId is NULL;
-- once the above conversion is run successfully then the following tables can be dropped
-- DROP TABLE rbc_criterion_ratings;
-- DROP TABLE rbc_rubric_criterions;
-- SAK-46178 END

-- SAK-46257 START
ALTER TABLE CONV_POSTS ADD DEPTH INT DEFAULT null NULL;
ALTER TABLE CONV_TOPIC_STATUS ADD POSTED BIT DEFAULT 0 NULL;
ALTER TABLE CONV_TOPICS ADD DUE_DATE datetime DEFAULT null NULL;
ALTER TABLE CONV_TOPICS ADD HIDE_DATE datetime DEFAULT null NULL;
ALTER TABLE CONV_TOPICS ADD LOCK_DATE datetime DEFAULT null NULL;
ALTER TABLE CONV_TOPICS ADD SHOW_DATE datetime DEFAULT null NULL;
ALTER TABLE CONV_POSTS ADD HOW_ACTIVE INT DEFAULT null NULL;
ALTER TABLE CONV_COMMENTS ADD TOPIC_ID VARCHAR(36) NOT NULL;
ALTER TABLE CONV_POSTS ADD NUMBER_OF_THREAD_REACTIONS INT DEFAULT null NULL;
ALTER TABLE CONV_POSTS ADD NUMBER_OF_THREAD_REPLIES INT DEFAULT null NULL;
ALTER TABLE CONV_POSTS ADD PARENT_THREAD_ID VARCHAR(36) NULL;
ALTER TABLE CONV_TOPICS ADD MUST_POST_BEFORE_VIEWING BIT DEFAULT 0 NULL;

CREATE INDEX conv_topics_site_creator_idx ON CONV_TOPICS (SITE_ID, CREATOR);
CREATE INDEX conv_posts_parent_thread_idx ON CONV_POSTS (PARENT_THREAD_ID);
CREATE INDEX conv_posts_topic_creator_idx ON CONV_POSTS (TOPIC_ID, CREATOR);
CREATE INDEX conv_comments_topic_idx ON CONV_COMMENTS (TOPIC_ID);

ALTER TABLE CONV_COMMENTS DROP FOREIGN KEY FK5ivsmxyitqpbm7pmdnu3lnmyi;
ALTER TABLE CONV_POSTS DROP FOREIGN KEY FKc21ukywsqsqilxlsdrg4x6qka;
ALTER TABLE CONV_USER_STATISTICS DROP FOREIGN KEY FKi9pfkqq0396p0kl718e9mrakk;
ALTER TABLE CONV_POST_REACTION_TOTALS DROP FOREIGN KEY FKirwlickqy5sf8o9ejk1qkuit6;
ALTER TABLE CONV_TOPIC_REACTIONS DROP FOREIGN KEY FKpwv7vrkag66g9kq6gghtc4uy1;
ALTER TABLE CONV_POSTS DROP FOREIGN KEY FKqaspmpv6ull7whideia5i2cnb;
ALTER TABLE CONV_TOPIC_REACTION_TOTALS DROP FOREIGN KEY FKqu7eyh63vtkowyqoqa9xy7wmq;
ALTER TABLE CONV_POST_REACTIONS DROP FOREIGN KEY FKqv38yghf2km7vq1i717xywih6;
-- SAK-46257 END

-- SAK-47231 START
ALTER TABLE CONV_POST_STATUS MODIFY POST_ID VARCHAR(36);
ALTER TABLE CONV_POST_STATUS MODIFY TOPIC_ID VARCHAR(36);
ALTER TABLE CONV_TOPIC_STATUS MODIFY TOPIC_ID VARCHAR(36);
-- SAK-47231 END

--------------------- End 22.0 -> 22.1 ------------------------------

------------------- Begin 22.1 -> 22.2 ------------------------------

-- SAK-47837 start
ALTER TABLE rbc_returned_criterion_out DROP FOREIGN KEY FK3sroha5yjh3cbvq0on02wf3fk;
ALTER TABLE rbc_criterion_outcome DROP FOREIGN KEY FKalvarr6g412wt7wto6tutsddu;

ALTER TABLE rbc_rating DROP COLUMN order_index;
ALTER TABLE rbc_criterion DROP COLUMN ownerId;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN siteId;
ALTER TABLE rbc_rating MODIFY criterion_id BIGINT NOT NULL;
ALTER TABLE rbc_rating ALTER criterion_id DROP DEFAULT;
ALTER TABLE rbc_tool_item_rbc_assoc MODIFY rubric_id BIGINT NOT NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ALTER rubric_id DROP DEFAULT;

CREATE INDEX rbc_tool_item ON rbc_tool_item_rbc_assoc(toolId, itemId);
DROP INDEX rbc_tool_item_owner ON rbc_tool_item_rbc_assoc;
-- SAK-47837 end

-------------------- End 22.1 -> 22.2 -------------------------------

-------- Missed snippet that should have been in 22.0 -> 22.1 -------

-- SAK-47291
UPDATE gb_gradable_object_t SET EXTERNAL_APP_NAME = 'sakai.assignment.grades' WHERE EXTERNAL_ID LIKE '/assignment/a/%';
UPDATE gb_gradable_object_t SET EXTERNAL_APP_NAME = 'sakai.lessonbuildertool' WHERE EXTERNAL_ID LIKE 'lesson-builder:%';
UPDATE gb_gradable_object_t SET EXTERNAL_APP_NAME = 'sakai.attendance' WHERE EXTERNAL_ID LIKE 'sakai.attendance.%';
UPDATE gb_gradable_object_t SET EXTERNAL_APP_NAME = 'sakai.samigo' WHERE EXTERNAL_ID REGEXP '^[0-9]+$';
-- END SAK-47291
