---------------------------------------------------------------
-- Oracle conversion script for OWL 20.2-owl6.1 to 22.3-owl1 --
---------------------------------------------------------------

----------------------- Begin 20.2 -> 20.3 ---------------------

-- START SAK-42371
ALTER TABLE rbc_evaluation ADD status NUMBER(1,0) DEFAULT 1 NOT NULL;
UPDATE rbc_evaluation SET status = 2;
-- END SAK-42371

-- SAK-44810 - Add $Resource.id.history
-- This needs to rename a column in the DB because of a bug that keeps "settings"
-- from working as needed for this feature.
ALTER TABLE lti_tools RENAME COLUMN allowsettings TO allowsettings_ext;
-- If autoDDL somehow already ran and created allowsettings_ext - then you need
-- to copy data from the old column and delete it
-- UPDATE lti_tools SET allowsettings_ext=allowsettings;
-- ALTER TABLE lti_tools DROP COLUMN allowsettings;
-- END SAK-44810

-- SAK-41502
ALTER TABLE GB_GRADING_EVENT_T ADD IS_EXCLUDED NUMBER(10, 0) DEFAULT 0 NOT NULL;
-- END SAK-41502

------------------------ End 20.2 -> 20.3 ---------------------------

----------- No Oracle database changes for 20.4 ---------------------

----------------------- Begin 20.4 -> 20.5 --------------------------

-- START SAK-44489
CREATE SEQUENCE BULLHORN_ALERTS_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;
-- END SAK-44489

------------------------ End 20.4 -> 20.5 ---------------------------

----------- No Oracle database changes for 20.6 ---------------------

------------------------ Begin 21.0 ---------------------------------

-- clear unchanged bundle properties
DELETE from SAKAI_MESSAGE_BUNDLE where PROP_VALUE is NULL;

-- this constraint may have been missed, it is ok if this line fails just comment it out
ALTER TABLE CONTENTREVIEW_ITEM ADD CONSTRAINT UK_8dngr1v68kkv4u11c1nvrjj1l UNIQUE (PROVIDERID, CONTENTID);

-- SAK-30079
ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY AUTO_FORWARD NUMBER(10, 0) DEFAULT 2 NOT NULL;

-- SAK-43826 : Rubrics: Support weighted criterions
ALTER TABLE rbc_rubric ADD weighted NUMBER(1, 0) DEFAULT 0 NOT NULL;
ALTER TABLE rbc_criterion ADD weight FLOAT DEFAULT 0;

-- SAK-44637 - Make the Lessons Placement checkbox work
-- Note that SAK-44636 already added the column in sakai_20_1-20_2_mysql_conversion.sql
-- It is included here and commented out in case you need it.
-- ALTER TABLE lti_tools ADD pl_lessonsselection NUMBER(1, 0) DEFAULT 0;
-- Existing records needed to be switched on right before the feature is used
UPDATE lti_tools SET pl_lessonsselection = 1;
-- END SAK-44637

-- SAK-45174 Rubrics metadata datetime conversion
ALTER TABLE rbc_criterion DROP COLUMN created;
ALTER TABLE rbc_criterion DROP COLUMN modified;
ALTER TABLE rbc_evaluation DROP COLUMN created;
ALTER TABLE rbc_evaluation DROP COLUMN modified;
ALTER TABLE rbc_rating DROP COLUMN created;
ALTER TABLE rbc_rating DROP COLUMN modified;
ALTER TABLE rbc_rubric DROP COLUMN created;
ALTER TABLE rbc_rubric DROP COLUMN modified;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN created;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN modified;

ALTER TABLE rbc_criterion ADD created TIMESTAMP NULL;
ALTER TABLE rbc_criterion ADD modified TIMESTAMP NULL;
ALTER TABLE rbc_evaluation ADD created TIMESTAMP NULL;
ALTER TABLE rbc_evaluation ADD modified TIMESTAMP NULL;
ALTER TABLE rbc_rating ADD created TIMESTAMP NULL;
ALTER TABLE rbc_rating ADD modified TIMESTAMP NULL;
ALTER TABLE rbc_rubric ADD created TIMESTAMP NULL;
ALTER TABLE rbc_rubric ADD modified TIMESTAMP NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD created TIMESTAMP NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD modified TIMESTAMP NULL;

UPDATE rbc_criterion SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_criterion SET modified = current_timestamp WHERE modified IS NULL;
UPDATE rbc_evaluation SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_evaluation SET modified = current_timestamp WHERE modified IS NULL;
UPDATE rbc_rating SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_rating SET modified = current_timestamp WHERE modified IS NULL;
UPDATE rbc_rubric SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_rubric SET modified = current_timestamp WHERE modified IS NULL;
UPDATE rbc_tool_item_rbc_assoc SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_tool_item_rbc_assoc SET modified = current_timestamp WHERE modified IS NULL;
-- END SAK-45174

-- SAK-44019
ALTER TABLE ASN_ASSIGNMENT ADD CONTENT_ID NUMBER(10, 0);
ALTER TABLE ASN_ASSIGNMENT ADD CONTENT_LAUNCH_NEW_WINDOW NUMBER(1, 0) DEFAULT 0;
-- END SAK-44019

-- SAK-45184
CREATE TABLE FILE_CONVERSION_QUEUE (
    ID                   NUMBER(19,0) NOT NULL,
    ATTEMPTS             NUMBER(10,0) NOT NULL,
    LAST_ATTEMPT_STARTED TIMESTAMP,
    REFERENCE            VARCHAR2(255 CHAR) NOT NULL,
    STATUS               VARCHAR2(16 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_FCI_REF_TYPE ON FILE_CONVERSION_QUEUE (REFERENCE);

create table MFR_DRAFT_RECIPIENT_T (
    ID           NUMBER(19,0) NOT NULL,
    BCC          NUMBER(1,0) DEFAULT 0 NOT NULL,
    DRAFT_ID     NUMBER(19,0) NOT NULL,
    RECIPIENT_ID VARCHAR2(255 CHAR) NOT NULL,
    TYPE         NUMBER(10,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE MFR_DRAFT_RECIPIENT_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;

CREATE INDEX MFR_DRAFT_REC_MSG_ID_I ON MFR_DRAFT_RECIPIENT_T (DRAFT_ID);

create table TASKS (
    ID          NUMBER(19,0) NOT NULL,
    DESCRIPTION VARCHAR2(255 CHAR) NOT NULL,
    DUE         TIMESTAMP,
    REFERENCE   VARCHAR2(255 CHAR) NOT NULL,
    SITE_ID     VARCHAR2(99 CHAR),
    STARTS      TIMESTAMP,
    SYSTEM      NUMBER(1,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE TASKS_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;

CREATE INDEX IDX_TASKS_REF_TYPE ON TASKS (REFERENCE);

create table USER_TASKS (
    ID           NUMBER(19,0) NOT NULL,
    COMPLETE     NUMBER(1,0),
    NOTES        CLOB,
    PRIORITY     NUMBER(10,0) NOT NULL,
    SOFT_DELETED NUMBER(1,0),
    USER_ID      VARCHAR2(99 CHAR) NOT NULL,
    TASK_ID      NUMBER(19,0) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FKMJ3LSH7WX4O7S7I6HY80TBPSN FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID)
);

CREATE SEQUENCE USER_TASKS_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;

CREATE INDEX IDX_USER_TASK ON USER_TASKS (USER_ID, TASK_ID);

CREATE INDEX FK_USER_TASKS_TASK_ID ON USER_TASKS (TASK_ID);

ALTER TABLE rbc_tool_item_rbc_assoc ADD active NUMBER(1,0) DEFAULT 1 NOT NULL;

ALTER TABLE rbc_tool_item_rbc_assoc DROP CONSTRAINT UKQ4BTC0DFYMI80BB5MP3VP3R7U;

CREATE INDEX FK1yhjvx9pxp5e76ijo0s6ahvsa ON rbc_tool_item_rbc_assoc(rubric_id);

DROP INDEX contentreview_provider_id_idx;

CREATE INDEX contentreview_provider_id_idx ON CONTENTREVIEW_ITEM(EXTERNALID);

-- LTI
ALTER TABLE lti_content ADD DESCRIPTION CLOB;
ALTER TABLE lti_content ADD protect NUMBER(1,0) DEFAULT 0;
ALTER TABLE lti_content DROP COLUMN sha256;
ALTER TABLE lti_tools ADD pl_privacy NUMBER(1, 0) DEFAULT 0;
ALTER TABLE lti_tools ADD pl_coursenav NUMBER(1, 0) DEFAULT 0;
ALTER TABLE lti_tools ADD lti13_auto_token VARCHAR2(1024 CHAR);
ALTER TABLE lti_tools ADD lti13_auto_state NUMBER(38,0);
ALTER TABLE lti_tools ADD lti13_auto_registration CLOB;

ALTER TABLE lti_tools RENAME COLUMN lti13_tool_keyset TO lti13_tool_keyset_old;
ALTER TABLE lti_tools ADD lti13_tool_keyset VARCHAR2(1024 CHAR);
UPDATE lti_tools SET lti13_tool_keyset = TO_CHAR(lti13_tool_keyset_old);
ALTER TABLE lti_tools DROP COLUMN lti13_tool_keyset_old;

ALTER TABLE lti_tools DROP COLUMN lti13_tool_kid;
ALTER TABLE lti_tools DROP COLUMN lti13_tool_private;
ALTER TABLE lti_tools DROP COLUMN lti13_tool_public;
ALTER TABLE lti_tools DROP COLUMN sha256;


ALTER TABLE SAKAI_PERSON_T RENAME COLUMN PHONETIC_PRONUNCIATION TO PHONETIC_OLD;
ALTER TABLE SAKAI_PERSON_T ADD PHONETIC_PRONUNCIATION VARCHAR2(255 CHAR);
UPDATE SAKAI_PERSON_T SET PHONETIC_PRONUNCIATION = TO_CHAR(PHONETIC_OLD);
ALTER TABLE SAKAI_PERSON_T DROP COLUMN PHONETIC_OLD;


ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY AUTO_FORWARD NUMBER(10,0);
-- OWL: commenting these lines out, see OWL-5240 for rationale
-- DROP INDEX MFR_UNREAD_STATUS_I1;
-- CREATE INDEX MFR_UNREAD_STATUS_I1 ON MFR_UNREAD_STATUS_T(TOPIC_C);


-- Polls
ALTER TABLE POLL_OPTION MODIFY DELETED NUMBER(1, 0) DEFAULT 0 NOT NULL;
-- OWL: this line will fail because we have nulls in option_order, moving to step 2 --
-- ALTER TABLE POLL_OPTION MODIFY OPTION_ORDER NUMBER(10, 0) NOT NULL;
ALTER TABLE POLL_OPTION MODIFY OPTION_POLL_ID NUMBER(19,0) NOT NULL;
ALTER TABLE POLL_OPTION MODIFY OPTION_UUID VARCHAR2(255 CHAR) NOT NULL;

-- OWL: backfill null creation dates so the modify statement that follows can succeed
update poll_poll set poll_creation_date = poll_vote_open where poll_creation_date is null;
ALTER TABLE POLL_POLL MODIFY POLL_CREATION_DATE TIMESTAMP NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_DISPLAY_RESULT VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_IS_PUBLIC NUMBER(1, 0) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_LIMIT_VOTE NUMBER(1, 0) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_MAX_OPTIONS NUMBER(10,0) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_MIN_OPTIONS NUMBER(10,0) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_OWNER VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_SITE_ID VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_UUID VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_VOTE_CLOSE TIMESTAMP NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_VOTE_OPEN TIMESTAMP NOT NULL;

ALTER TABLE POLL_VOTE MODIFY VOTE_DATE TIMESTAMP NOT NULL;
ALTER TABLE POLL_VOTE MODIFY VOTE_IP VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_VOTE MODIFY VOTE_POLL_ID NUMBER(19,0) NOT NULL;
ALTER TABLE POLL_VOTE MODIFY VOTE_SUBMISSION_ID VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_VOTE MODIFY USER_ID VARCHAR2(255 CHAR) NOT NULL;


-- Site Setup Questions
ALTER TABLE SSQ_ANSWER MODIFY ANSWER VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE SSQ_ANSWER MODIFY FILL_IN_BLANK NUMBER(1,0) NOT NULL;
ALTER TABLE SSQ_ANSWER MODIFY ORDER_NUM NUMBER(10,0) NOT NULL;

ALTER TABLE SSQ_QUESTION MODIFY IS_CURRENT VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE SSQ_QUESTION MODIFY MULTIPLE_ANSWERS NUMBER(1,0) NOT NULL;
ALTER TABLE SSQ_QUESTION MODIFY ORDER_NUM NUMBER(10,0) NOT NULL;
ALTER TABLE SSQ_QUESTION MODIFY REQUIRED NUMBER(1,0) NOT NULL;

ALTER TABLE SSQ_USER_ANSWER MODIFY SITE_ID VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE SSQ_USER_ANSWER MODIFY USER_ID VARCHAR2(255 CHAR) NOT NULL;

ALTER TABLE SSQ_SITETYPE_QUESTIONS MODIFY SITE_TYPE VARCHAR2(255 CHAR) NOT NULL;

-- END SAK-45184

------------------------ End 21.0 -----------------------------------

---------------------- Begin 21.0 -> 21.1 ---------------------------

-- START SAK-45137
UPDATE rbc_rating SET title = 'Title' WHERE title IS NULL;
ALTER TABLE rbc_rating MODIFY title VARCHAR2(255) NOT NULL;
-- ALTER TABLE rbc_rating ALTER title DROP DEFAULT;

-- UPDATE rbc_rating SET points = 0 WHERE points IS NULL;
-- ALTER TABLE rbc_rating MODIFY points FLOAT NOT NULL;
-- ALTER TABLE rbc_rating ALTER points DROP DEFAULT;
-- OWL: modified process for Oracle compatibility
UPDATE rbc_rating SET points = 0 WHERE points IS NULL;
ALTER TABLE rbc_rating ADD points2 FLOAT;
UPDATE rbc_rating SET points2 = points;
ALTER TABLE rbc_rating DROP COLUMN points;
ALTER TABLE rbc_rating RENAME COLUMN points2 TO points;
ALTER TABLE rbc_rating MODIFY points FLOAT NOT NULL;
-- END SAK-45137

-- START SAK-45601
CREATE TABLE TINCANAPI_EVENT (
EVENT VARCHAR2(32) NOT NULL,
VERB VARCHAR2(64) NOT NULL,
ORIGIN VARCHAR2(64) NOT NULL,
OBJECT VARCHAR2(64) NOT NULL,
EVENT_SUPPLIER VARCHAR2(64),
PRIMARY KEY (EVENT));

-- Initial data that were in the ifs:
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('user.login', 'initialized', 'sakai.system', 'session-started', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('user.login.container', 'initialized', 'sakai.system', 'session-started', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('user.logout', 'exited', 'sakai.system', 'session-ended', 'logout');
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('annc.read', 'experienced', 'announcement', 'view-announcement', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('calendar.read', 'experienced', 'calendar', 'view-calendar', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('chat.new', 'responded', 'chat', 'view-chats', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('chat.read', 'experienced', 'chat', 'view-chats', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('content.read', 'interacted', 'sakai.resources', 'view-resource', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('content.new', 'shared', 'sakai.resources', 'add-resource', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('content.revise', 'shared', 'sakai.resources', 'edit-resource', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('gradebook.read', 'experienced', 'gradebook', 'view-grades', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('lessonbuilder.page.read', 'experienced', 'lessonbuilder', 'view-lesson', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('lessonbuilder.item.read', 'experienced', 'lessonbuilder', 'view-lesson', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('news.read', 'experienced', 'news', 'view-news', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('podcast.read', 'experienced', 'podcast', 'view-podcast', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('podcast.read.public', 'experienced', 'podcast', 'view-podcast', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('podcast.read.site', 'experienced', 'podcast', 'view-podcast', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('syllabus.read', 'experienced', 'syllabus', 'view-syllabus', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('webcontent.read', 'experienced', 'webcontent', 'view-web-content', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('wiki.new', 'initialized', 'rwiki', 'add-wiki-page', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('wiki.revise', 'shared', 'rwiki', 'edit-wiki-page', null);
INSERT INTO TINCANAPI_EVENT (EVENT, VERB, ORIGIN, OBJECT, EVENT_SUPPLIER) VALUES('wiki.read', 'experienced', 'rwiki', 'view-wiki-page', null);
-- END SAK-45601

-- START SAK-45575
CREATE INDEX IDX_FCI_STATUS ON FILE_CONVERSION_QUEUE(STATUS);
-- END SAK-45575

-- START SAK-45580
-- OWL: the drop constraint below was required on sakdev to drop the index, could not find similar on qat/prd
ALTER TABLE file_conversion_queue DROP CONSTRAINT UK_J0T1GD58BUW5B0CWXAYINCY09;
DROP INDEX IDX_FCI_REF_TYPE;
-- END SAK-45580

---------------------- End 21.0 -> 21.1 -----------------------------

-------------------- Begin 21.1 -> 21.2 -----------------------------

-- SAK-45435
ALTER TABLE lti_tools ADD lti13_platform_public_old CLOB;
ALTER TABLE lti_tools ADD lti13_platform_public_old_at DATE DEFAULT NULL;
-- End SAK-45435

-- SAK-43510
ALTER TABLE SAKAI_PERSON_T ADD PRONOUNS VARCHAR2(255);
-- End SAK-43510

-- SAK-45491
ALTER TABLE lti_tools ADD lti13_platform_public_next CLOB;
ALTER TABLE lti_tools ADD lti13_platform_public_next_at DATE NULL;
ALTER TABLE lti_tools ADD lti13_platform_private_next CLOB;
-- End SAK-45491

-- Start SAK-45692
ALTER TABLE FILE_CONVERSION_QUEUE ADD CONSTRAINT UK_j0t1gd58buw5b0cwxayincy09 UNIQUE (REFERENCE);
-- End SAK-45692

------- OWLTODO: Snippet below commented out for now, pending further investigation of impact ----------
-- Start SAK-46414
-- ALTER TABLE SAM_MEDIA_T DROP COLUMN ISHTMLINLINE;
-- ALTER TABLE SAM_MEDIA_T DROP COLUMN MEDIA;
-- End SAK-46414

---------------------- End 21.1 -> 21.2 -----------------------------

------------------- Begin 21.2 -> 21.3 ------------------------------

-- Start SAK-41604
ALTER TABLE RBC_EVALUATION ADD EVALUATED_ITEM_OWNER_TYPE NUMBER(1,0);
-- End SAK-41604

-- SAK-46977
-- Add the Functions
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'sitestats.all');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'sitestats.own');

-- --------------------------------------------------------------------------------------------------------------------------------------
-- backfill new permission into existing realms
-- --------------------------------------------------------------------------------------------------------------------------------------

-- for each realm that has a role matching something in this table, we will add to that role the function from this table
CREATE TABLE PERMISSIONS_SRC_TEMP (ROLE_NAME VARCHAR(99), FUNCTION_NAME VARCHAR(99));

INSERT INTO PERMISSIONS_SRC_TEMP VALUES('maintain','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Instructor','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Content Designer','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Course Coordinator','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Grade Admin','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Librarian','sitestats.all');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Secondary Instructor','sitestats.all');
-- OWL: we will not be granting students the 'sitestats.own' permission
-- INSERT INTO PERMISSIONS_SRC_TEMP VALUES('access','sitestats.own');
-- INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Student','sitestats.own');

-- lookup the role and function number
CREATE TABLE PERMISSIONS_TEMP (ROLE_KEY INTEGER, FUNCTION_KEY INTEGER);
INSERT INTO PERMISSIONS_TEMP (ROLE_KEY, FUNCTION_KEY)
SELECT SRR.ROLE_KEY, SRF.FUNCTION_KEY
FROM PERMISSIONS_SRC_TEMP TMPSRC
JOIN SAKAI_REALM_ROLE SRR ON (TMPSRC.ROLE_NAME = SRR.ROLE_NAME)
JOIN SAKAI_REALM_FUNCTION SRF ON (TMPSRC.FUNCTION_NAME = SRF.FUNCTION_NAME);

-- insert the new function into the roles of any existing realm that has the role (don't convert the "!site.helper")
INSERT INTO SAKAI_REALM_RL_FN (REALM_KEY, ROLE_KEY, FUNCTION_KEY)
SELECT
    SRRFD.REALM_KEY, SRRFD.ROLE_KEY, TMP.FUNCTION_KEY
FROM
    (SELECT DISTINCT SRRF.REALM_KEY, SRRF.ROLE_KEY FROM SAKAI_REALM_RL_FN SRRF) SRRFD
    JOIN PERMISSIONS_TEMP TMP ON (SRRFD.ROLE_KEY = TMP.ROLE_KEY)
    JOIN SAKAI_REALM SR ON (SRRFD.REALM_KEY = SR.REALM_KEY)
    WHERE SR.REALM_ID != '!site.helper'
    AND NOT EXISTS (
        SELECT 1
            FROM SAKAI_REALM_RL_FN SRRFI
            WHERE SRRFI.REALM_KEY=SRRFD.REALM_KEY AND SRRFI.ROLE_KEY=SRRFD.ROLE_KEY AND SRRFI.FUNCTION_KEY=TMP.FUNCTION_KEY
    );

-- clean up the temp tables
DROP TABLE PERMISSIONS_TEMP;
DROP TABLE PERMISSIONS_SRC_TEMP;

-- END SAK-46977

---------------------- End 21.2 -> 21.3 -----------------------------

-------------------- Begin 21.3 -> 21.4 -----------------------------

-- SAK-45330 START
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'rubrics.manager.view');

CREATE TABLE PERMISSIONS_SRC_TEMP (ROLE_NAME VARCHAR(99), FUNCTION_NAME VARCHAR(99));

INSERT INTO PERMISSIONS_SRC_TEMP VALUES('maintain','rubrics.manager.view');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Instructor','rubrics.manager.view');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Course Coordinator','rubrics.manager.view');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Grade Admin','rubrics.manager.view');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES('Secondary Instructor','rubrics.manager.view');

CREATE TABLE PERMISSIONS_TEMP (ROLE_KEY INTEGER, FUNCTION_KEY INTEGER);
INSERT INTO PERMISSIONS_TEMP (ROLE_KEY, FUNCTION_KEY)
SELECT SRR.ROLE_KEY, SRF.FUNCTION_KEY
FROM PERMISSIONS_SRC_TEMP TMPSRC
JOIN SAKAI_REALM_ROLE SRR ON (TMPSRC.ROLE_NAME = SRR.ROLE_NAME)
JOIN SAKAI_REALM_FUNCTION SRF ON (TMPSRC.FUNCTION_NAME = SRF.FUNCTION_NAME);

-- insert the new function into the roles of any existing realm that has the role (don't convert the "!site.helper")
INSERT INTO SAKAI_REALM_RL_FN (REALM_KEY, ROLE_KEY, FUNCTION_KEY)
SELECT
    SRRFD.REALM_KEY, SRRFD.ROLE_KEY, TMP.FUNCTION_KEY
FROM
    (SELECT DISTINCT SRRF.REALM_KEY, SRRF.ROLE_KEY FROM SAKAI_REALM_RL_FN SRRF) SRRFD
    JOIN PERMISSIONS_TEMP TMP ON (SRRFD.ROLE_KEY = TMP.ROLE_KEY)
    JOIN SAKAI_REALM SR ON (SRRFD.REALM_KEY = SR.REALM_KEY)
    WHERE SR.REALM_ID != '!site.helper'
    AND NOT EXISTS (
        SELECT 1
            FROM SAKAI_REALM_RL_FN SRRFI
            WHERE SRRFI.REALM_KEY=SRRFD.REALM_KEY AND SRRFI.ROLE_KEY=SRRFD.ROLE_KEY AND SRRFI.FUNCTION_KEY=TMP.FUNCTION_KEY
    );

-- clean up the temp tables
DROP TABLE PERMISSIONS_TEMP;
DROP TABLE PERMISSIONS_SRC_TEMP;

-- SAK-45330 END

---------------------- End 21.3 -> 21.4 -----------------------------

------------------------- Begin 22.0 --------------------------------

-- SAK-45565
ALTER TABLE lesson_builder_groups RENAME COLUMN groups TO item_groups;
ALTER TABLE lesson_builder_items RENAME COLUMN groups TO item_groups;
ALTER TABLE tasks RENAME COLUMN SYSTEM TO SYSTEM_TASK;
-- SAK-45565

-- SAK-44967
ALTER TABLE gb_gradebook_t ADD allow_compare_grades NUMBER(1,0) DEFAULT 0 NOT NULL ;
ALTER TABLE gb_gradebook_t ADD comparing_display_firstnames NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_display_surnames NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_display_comments NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_display_allitems NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE gb_gradebook_t ADD comparing_randomizedata NUMBER(1,0) DEFAULT 0 NOT NULL;
-- End SAK-44967

-- Conversations
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.anonymous.view');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.comment.create');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.comment.delete.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.comment.delete.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.comment.update.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.comment.update.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.moderate');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.post.create');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.post.delete.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.post.delete.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.post.react');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.post.update.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.post.update.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.post.upvote');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.roletype.instructor');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.statistics.view');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.tag.create');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.topic.create');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.topic.delete.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.topic.delete.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.topic.pin');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.topic.tag');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.topic.update.any');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.topic.update.own');
INSERT INTO SAKAI_REALM_FUNCTION (FUNCTION_KEY, FUNCTION_NAME) VALUES(SAKAI_REALM_FUNCTION_SEQ.NEXTVAL, 'conversations.topic.view.groups');

-- OWL: we are not enabling this tool so will not backfill permissions --

-- End Conversations

-- SAK-46022
ALTER TABLE COMMONS_POST ADD PRIORITY NUMBER(1) DEFAULT 0 NOT NULL;
-- End SAK-46022

-- SAK-46685
ALTER TABLE ASN_ASSIGNMENT ADD ESTIMATE_REQUIRED CHAR(1) DEFAULT '0' NOT NULL;
ALTER TABLE ASN_ASSIGNMENT ADD ESTIMATE VARCHAR2(255) NULL;
ALTER TABLE ASN_SUBMISSION_SUBMITTER ADD TIME_SPENT VARCHAR2(255) NULL;
ALTER TABLE ASN_ASSIGNMENT ADD CONSTRAINT CHECK_IS_ESTIMATE_REQUIRED CHECK (ESTIMATE_REQUIRED IN ('0', '1'));

CREATE TABLE TIMESHEET_ENTRY (
ID number(22) NOT NULL,
REFERENCE VARCHAR2(255) NOT NULL,
USER_ID VARCHAR2(99),
START_TIME TIMESTAMP(6) NOT NULL,
DURATION VARCHAR2(255) NOT NULL,
TEXT_COMMENT VARCHAR2(4000) NULL,
PRIMARY KEY (ID)
);

CREATE INDEX IDX_TIMESHEETENTRY_REF_USER ON TIMESHEET_ENTRY(REFERENCE, USER_ID);
CREATE SEQUENCE TIMESHEET_S;
-- End SAK-46685

-- SAK-46021
CREATE TABLE COMMONS_LIKE (
USER_ID VARCHAR2(99) NOT NULL,
POST_ID VARCHAR2(36) NOT NULL,
VOTE NUMBER(1) DEFAULT 0 NOT NULL,
MODIFIED_DATE TIMESTAMP(6),
CONSTRAINT commons_like_pk PRIMARY KEY (USER_ID, POST_ID)
);
--End SAK-46021

-- SAK-46137
ALTER TABLE SAKAI_PERSON_T ADD PRINCIPAL_NAME_PRIOR varchar2(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD SCOPED_AFFILIATION varchar2(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD TARGETED_ID varchar2(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD ASSURANCE varchar2(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD UNIQUE_ID varchar2(255) DEFAULT NULL;
ALTER TABLE SAKAI_PERSON_T ADD ORCID varchar2(255) DEFAULT NULL;
-- End SAK-46137

-- SAK-46085
ALTER TABLE PROFILE_SOCIAL_INFO_T ADD INSTAGRAM_URL VARCHAR2(255) NULL;
--End SAK-46085

-- SAK-46686
ALTER TABLE GB_GRADE_RECORD_T ADD ENTERED_POINTS FLOAT DEFAULT NULL;
--End SAK-46686

-- SAK-45987
CREATE TABLE RBC_RETURNED_CRITERION_OUT (
  ID NUMBER(19) NOT NULL,
  COMMENTS CLOB DEFAULT NULL,
  CRITERION_ID NUMBER(19) DEFAULT NULL,
  POINTS FLOAT DEFAULT NULL,
  POINTSADJUSTED NUMBER(1,0) NOT NULL,
  SELECTED_RATING_ID NUMBER(19) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_RBC_RETURNED_CRITERION_ID FOREIGN KEY (CRITERION_ID) REFERENCES RBC_CRITERION (ID)
);

CREATE SEQUENCE RBC_RET_CRIT_OUT_SEQ;

CREATE INDEX FK_RBC_RET_CRIT_OUT_CRIT_ID ON RBC_RETURNED_CRITERION_OUT (CRITERION_ID);

CREATE TABLE RBC_RETURNED_EVALUATION (
  ID NUMBER(19) NOT NULL,
  ORIGINAL_EVALUATION_ID NUMBER(19) NOT NULL,
  OVERALLCOMMENT VARCHAR2(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE RBC_RET_EVAL_SEQ;

CREATE INDEX RBC_RET_ORIG_ID ON  RBC_RETURNED_EVALUATION(ORIGINAL_EVALUATION_ID);

CREATE TABLE RBC_RETURNED_CRITERION_OUTS (
  RBC_RETURNED_EVALUATION_ID NUMBER(19) NOT NULL,
  RBC_RETURNED_CRITERION_OUT_ID NUMBER(19) NOT NULL UNIQUE,
  CONSTRAINT RETURNED_CRITERION_OUT_ID_FK FOREIGN KEY (RBC_RETURNED_CRITERION_OUT_ID) REFERENCES RBC_RETURNED_CRITERION_OUT (ID),
  CONSTRAINT RETURNED_EVALUTION_ID_FK FOREIGN KEY (RBC_RETURNED_EVALUATION_ID) REFERENCES RBC_RETURNED_EVALUATION (ID)
);

CREATE INDEX RETURNED_CRIT_OUT_ID_KEY ON RBC_RETURNED_CRITERION_OUTS(RBC_RETURNED_CRITERION_OUT_ID);
CREATE INDEX RETURNED_EVALUATION_ID_KEY ON RBC_RETURNED_CRITERION_OUTS(RBC_RETURNED_EVALUATION_ID);
-- End SAK-45987

-- SAK-45092
CREATE TABLE CONV_COMMENTS (
  COMMENT_ID VARCHAR2(36) NOT NULL,
  LOCKED NUMBER(1,0) DEFAULT 0 NULL,
  MESSAGE VARCHAR2(255) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  CREATOR VARCHAR2(99) NULL,
  MODIFIED TIMESTAMP DEFAULT NULL NULL,
  MODIFIER VARCHAR2(99) NULL,
  SITE_ID VARCHAR2(99) NOT NULL,
  POST_ID VARCHAR2(36) NOT NULL,
  CONSTRAINT PK_CONV_COMMENTS PRIMARY KEY (COMMENT_ID)
);

CREATE TABLE CONV_POSTS (
  POST_ID VARCHAR2(36) NOT NULL,
  ANONYMOUS NUMBER(1,0) DEFAULT 0 NULL,
  DRAFT NUMBER(1,0) DEFAULT 0 NULL,
  HIDDEN NUMBER(1,0) DEFAULT 0 NULL,
  LOCKED NUMBER(1,0) DEFAULT 0 NULL,
  MESSAGE CLOB NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  CREATOR VARCHAR2(99) NULL,
  MODIFIED TIMESTAMP DEFAULT NULL NULL,
  MODIFIER VARCHAR2(99) NULL,
  NUMBER_OF_COMMENTS NUMBER(10,0) DEFAULT NULL NULL,
  PRIVATE_POST NUMBER(1,0) DEFAULT 0 NULL,
  SITE_ID VARCHAR2(99) NOT NULL,
  UPVOTES NUMBER(10,0) DEFAULT NULL NULL,
  PARENT_POST_ID VARCHAR2(36) NULL,
  TOPIC_ID VARCHAR2(36) NOT NULL,
  CONSTRAINT PK_CONV_POSTS PRIMARY KEY (POST_ID)
);

CREATE TABLE CONV_POST_REACTIONS (
  ID NUMBER(19,0) NOT NULL,
  REACTION NUMBER(10,0) NOT NULL,
  REACTION_STATE NUMBER(1,0) DEFAULT 0 NULL,
  USER_ID VARCHAR2(99) NOT NULL,
  POST_ID VARCHAR2(36) NOT NULL,
  CONSTRAINT PK_CONV_POST_REACTIONS PRIMARY KEY (ID)
);

CREATE TABLE CONV_POST_REACTION_TOTALS (
  ID NUMBER(19,0) NOT NULL,
  REACTION NUMBER(10,0) NOT NULL,
  TOTAL NUMBER(10,0) NOT NULL,
  POST_ID VARCHAR2(36) NOT NULL,
  CONSTRAINT PK_CONV_POST_REACTION_TOTALS PRIMARY KEY (ID)
);

CREATE TABLE CONV_POST_STATUS (
  ID NUMBER(19,0) NOT NULL,
  POST_ID VARCHAR2(255) NOT NULL,
  TOPIC_ID VARCHAR2(255) NOT NULL,
  UPVOTED NUMBER(1,0) DEFAULT 0 NULL,
  USER_ID VARCHAR2(99) NOT NULL,
  VIEWED NUMBER(1,0) DEFAULT 0 NULL,
  VIEWED_DATE TIMESTAMP DEFAULT NULL NULL,
  CONSTRAINT PK_CONV_POST_STATUS PRIMARY KEY (ID)
);

CREATE TABLE CONV_SETTINGS (
  ID NUMBER(19,0) NOT NULL,
  ALLOW_ANON_POSTING NUMBER(1,0) DEFAULT 0 NULL,
  ALLOW_BOOKMARKING NUMBER(1,0) DEFAULT 0 NULL,
  ALLOW_PINNING NUMBER(1,0) DEFAULT 0 NULL,
  ALLOW_REACTIONS NUMBER(1,0) DEFAULT 0 NULL,
  ALLOW_UPVOTING NUMBER(1,0) DEFAULT 0 NULL,
  DEFAULT_TOPIC_TYPE VARCHAR2(32) NULL,
  GUIDELINES CLOB NULL,
  REQUIRE_GUIDELINES_AGREEMENT NUMBER(1,0) DEFAULT 0 NULL,
  SITE_ID VARCHAR2(99) NOT NULL,
  SITE_LOCKED NUMBER(1,0) DEFAULT 0 NULL,
  CONSTRAINT PK_CONV_SETTINGS PRIMARY KEY (ID),
  UNIQUE (SITE_ID)
);

CREATE TABLE CONV_STATUS (
  ID NUMBER(19,0)  NOT NULL,
  GUIDELINES_AGREED NUMBER(1,0) DEFAULT 0 NULL,
  SITE_ID VARCHAR2(99) NOT NULL,
  USER_ID VARCHAR2(99) NOT NULL,
  CONSTRAINT PK_CONV_STATUS PRIMARY KEY (ID)
);

CREATE TABLE CONV_TAGS (
  TAG_ID NUMBER(19,0)  NOT NULL,
  DESCRIPTION VARCHAR2(255) NULL,
  LABEL VARCHAR2(255) NOT NULL,
  SITE_ID VARCHAR2(99) NOT NULL,
  CONSTRAINT PK_CONV_TAGS PRIMARY KEY (TAG_ID)
);

CREATE TABLE CONV_TOPICS (
  TOPIC_ID VARCHAR2(36) NOT NULL,
  ABOUT_REFERENCE VARCHAR2(255) NULL,
  ALLOW_ANONYMOUS_POSTS NUMBER(1,0) DEFAULT 0 NULL,
  ANONYMOUS NUMBER(1,0) DEFAULT 0 NULL,
  DRAFT NUMBER(1,0) DEFAULT 0 NULL,
  HIDDEN NUMBER(1,0) DEFAULT 0 NULL,
  HOW_ACTIVE NUMBER(10,0) DEFAULT NULL NULL,
  LAST_ACTIVITY TIMESTAMP DEFAULT NULL NULL,
  LOCKED NUMBER(1,0) DEFAULT 0 NULL,
  MESSAGE CLOB NULL,
  CREATED TIMESTAMP NOT NULL,
  CREATOR VARCHAR2(99) NULL,
  MODIFIED TIMESTAMP DEFAULT NULL NULL,
  MODIFIER VARCHAR2(99) NULL,
  PINNED NUMBER(1,0) DEFAULT 0 NULL,
  RESOLVED NUMBER(1,0) DEFAULT 0 NULL,
  SITE_ID VARCHAR2(99) NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  TOPIC_TYPE VARCHAR2(32) NULL,
  VISIBILITY VARCHAR2(32) NULL,
  CONSTRAINT PK_CONV_TOPICS PRIMARY KEY (TOPIC_ID)
);

CREATE TABLE CONV_TOPIC_GROUPS (
  TOPIC_ID VARCHAR2(36) NOT NULL,
  GROUP_ID VARCHAR2(255) NULL
);

CREATE TABLE CONV_TOPIC_REACTIONS (
  ID NUMBER(19,0)  NOT NULL,
  REACTION NUMBER(10,0) NOT NULL,
  REACTION_STATE NUMBER(1,0) DEFAULT 0 NULL,
  USER_ID VARCHAR2(99) NOT NULL,
  TOPIC_ID VARCHAR2(36) NOT NULL,
  CONSTRAINT PK_CONV_TOPIC_REACTIONS PRIMARY KEY (ID)
);

CREATE TABLE CONV_TOPIC_REACTION_TOTALS (
  ID NUMBER(19,0)  NOT NULL,
  REACTION NUMBER(10,0) NOT NULL,
  TOTAL NUMBER(10,0) NOT NULL,
  TOPIC_ID VARCHAR2(36) NOT NULL,
  CONSTRAINT PK_CONV_TOPIC_REACTION_TOTALS PRIMARY KEY (ID)
);

CREATE TABLE CONV_TOPIC_STATUS (
  ID NUMBER(19,0)  NOT NULL,
  BOOKMARKED NUMBER(1,0) DEFAULT 0 NULL,
  SITE_ID VARCHAR2(255) NOT NULL,
  TOPIC_ID VARCHAR2(255) NOT NULL,
  UNREAD NUMBER(10,0) DEFAULT NULL NULL,
  USER_ID VARCHAR2(99) NOT NULL,
  VIEWED NUMBER(1,0) DEFAULT 0 NULL,
  CONSTRAINT PK_CONV_TOPIC_STATUS PRIMARY KEY (ID)
);

CREATE TABLE CONV_TOPIC_TAGS (
  TOPIC_ID VARCHAR2(36) NOT NULL,
  TAG NUMBER(19,0) DEFAULT NULL NULL
);

CREATE TABLE CONV_USER_STATISTICS (
  ID NUMBER(19,0) NOT NULL,
  LAST_POST_DATE TIMESTAMP DEFAULT NULL NULL,
  NUMBER_OF_POSTS NUMBER(10,0) DEFAULT NULL NULL,
  NUMBER_OF_REACTIONS NUMBER(10,0) DEFAULT NULL NULL,
  NUMBER_OF_REPLIES NUMBER(10,0) DEFAULT NULL NULL,
  NUMBER_OF_UPVOTES NUMBER(10,0) DEFAULT NULL NULL,
  NUMBER_READ NUMBER(10,0) DEFAULT NULL NULL,
  USER_ID VARCHAR2(99) NOT NULL,
  TOPIC_ID VARCHAR2(36) NULL,
  CONSTRAINT PK_CONV_USER_STATISTICS PRIMARY KEY (ID)
);

ALTER TABLE CONV_STATUS ADD CONSTRAINT UniqueConvStatus UNIQUE (SITE_ID, USER_ID);
ALTER TABLE CONV_POST_REACTION_TOTALS ADD CONSTRAINT UniquePostReactionTotals UNIQUE (POST_ID, REACTION);
ALTER TABLE CONV_POST_REACTIONS ADD CONSTRAINT UniquePostReactions UNIQUE (POST_ID, USER_ID, REACTION);
ALTER TABLE CONV_POST_STATUS ADD CONSTRAINT UniquePostStatus UNIQUE (POST_ID, USER_ID);
ALTER TABLE CONV_TOPIC_REACTION_TOTALS ADD CONSTRAINT UniqueTopicReactionTotals UNIQUE (TOPIC_ID, REACTION);
ALTER TABLE CONV_TOPIC_REACTIONS ADD CONSTRAINT UniqueTopicReactions UNIQUE (TOPIC_ID, USER_ID, REACTION);
ALTER TABLE CONV_TOPIC_STATUS ADD CONSTRAINT UniqueTopicStatus UNIQUE (TOPIC_ID, USER_ID);

CREATE INDEX FKc21ukywsqsqilxlsdrg4x6qka ON CONV_POSTS(PARENT_POST_ID);
CREATE INDEX FKi9pfkqq0396p0kl718e9mrakk ON CONV_USER_STATISTICS(TOPIC_ID);
CREATE INDEX FKj8o3cwa4flprmopiaa1xxi91s ON CONV_TOPIC_GROUPS(TOPIC_ID);
CREATE INDEX FKrmek6b1bqs2jghppp27ph2dn9 ON CONV_TOPIC_TAGS(TOPIC_ID);
CREATE INDEX IDX3nridt976wgqrd0vxge273ctk ON CONV_POST_REACTIONS(POST_ID);
CREATE INDEX IDX4vl5kx35nbj7mm5tjc789pkrs ON CONV_POST_STATUS(POST_ID);
CREATE INDEX IDX59e65g24yqkm9d4omljmdk2i9 ON CONV_POSTS(SITE_ID);
CREATE INDEX IDX9tgexj1wml170sorc2agiac1i ON CONV_TAGS(SITE_ID);
CREATE INDEX IDXbb22xsa2tdsm7jv8v0w1rwxvh ON CONV_POST_REACTION_TOTALS(POST_ID);
CREATE INDEX IDXdsq2b214fvqnhxevs6ogx37po ON CONV_POST_REACTIONS(POST_ID, USER_ID);
CREATE INDEX IDXeisyrk9cbbkdmqo5on3e7pysg ON CONV_COMMENTS(SITE_ID);
CREATE INDEX IDXhw1kgsuv0qp47fvc8meopwaea ON CONV_POST_STATUS(TOPIC_ID, USER_ID);
CREATE INDEX IDXih3xad6e7nljy7cw8dsinq5j4 ON CONV_POSTS(TOPIC_ID);
CREATE INDEX IDXjuusvvw52sys4e6fa9bn5rs6t ON CONV_USER_STATISTICS(USER_ID);
CREATE INDEX IDXl2syeorinknc7t5e8jrctam81 ON CONV_POST_STATUS(USER_ID);
CREATE INDEX IDXo21yr7ncf5o3qrtwv36pc083k ON CONV_TOPICS(SITE_ID);
CREATE INDEX IDXp4bavayq4l7jiplafk6swbst ON CONV_TOPIC_REACTION_TOTALS(TOPIC_ID);
CREATE INDEX IDXq3yulh1p20c1eggq63he9mvoh ON CONV_TOPIC_REACTIONS(TOPIC_ID, USER_ID);
CREATE INDEX IDXqu1kvjnw63lom1ymespiiomqm ON CONV_TOPIC_REACTIONS(TOPIC_ID);
CREATE INDEX IDXtf2j5cl6yv4mrhxb06oc4s4hu ON CONV_COMMENTS(POST_ID);

ALTER TABLE CONV_COMMENTS ADD CONSTRAINT FK5ivsmxyitqpbm7pmdnu3lnmyi FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID);
ALTER TABLE CONV_POSTS ADD CONSTRAINT FKc21ukywsqsqilxlsdrg4x6qka FOREIGN KEY (PARENT_POST_ID) REFERENCES CONV_POSTS (POST_ID);
ALTER TABLE CONV_USER_STATISTICS ADD CONSTRAINT FKi9pfkqq0396p0kl718e9mrakk FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_POST_REACTION_TOTALS ADD CONSTRAINT FKirwlickqy5sf8o9ejk1qkuit6 FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID);
ALTER TABLE CONV_TOPIC_GROUPS ADD CONSTRAINT FKj8o3cwa4flprmopiaa1xxi91s FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_TOPIC_REACTIONS ADD CONSTRAINT FKpwv7vrkag66g9kq6gghtc4uy1 FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_POSTS ADD CONSTRAINT FKqaspmpv6ull7whideia5i2cnb FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_TOPIC_REACTION_TOTALS ADD CONSTRAINT FKqu7eyh63vtkowyqoqa9xy7wmq FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_POST_REACTIONS ADD CONSTRAINT FKqv38yghf2km7vq1i717xywih6 FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID);
ALTER TABLE CONV_TOPIC_TAGS ADD CONSTRAINT FKrmek6b1bqs2jghppp27ph2dn9 FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);

-- END SAK-45092

------------------------- End 22.0 ----------------------------------

------------------- Begin 22.0 -> 22.1 ------------------------------

-- SAK-46436 START
ALTER TABLE TASKS ADD TASK_OWNER VARCHAR2(99 CHAR);

CREATE TABLE TASKS_ASSIGNED
(
   ID              NUMBER(19,0) NOT NULL,
   TASK_ID         NUMBER(19,0) NOT NULL,
   ASSIGNATION_TYPE   VARCHAR2(5) NOT NULL,
   OBJECT_ID       VARCHAR2(99 CHAR),
   PRIMARY KEY(ID),
   CONSTRAINT FK_TASKS_ASSIGNED_TASKS FOREIGN KEY(TASK_ID) REFERENCES TASKS (ID)
);

CREATE SEQUENCE TASKS_ASSIGNED_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;
CREATE INDEX IDX_TASKS_ASSIGNED ON TASKS_ASSIGNED (TASK_ID);
-- SAK-46436 END

-- SAK-46986 START
CREATE TABLE TASK_GROUPS
(
    TASK_ID  NUMBER(19,0) NOT NULL,
    GROUP_ID VARCHAR2(99 CHAR) NULL,
    CONSTRAINT FK7x7ajup3bwe3hcwq057evmala FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID)
);

CREATE INDEX FK7x7ajup3bwe3hcwq057evmala ON TASK_GROUPS (TASK_ID);
-- SAK-46986 END

-- SAK-46178 START
ALTER TABLE rbc_rating ADD order_index INT DEFAULT null NULL;
ALTER TABLE rbc_criterion ADD order_index INT DEFAULT null NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD siteId VARCHAR(99) NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD CONSTRAINT rbc_item_rubric UNIQUE (itemId, rubric_id);
ALTER TABLE rbc_criterion_ratings DROP CONSTRAINT FK2ecdorwm3nm2ytyg9uvxlik53;
ALTER TABLE rbc_criterion_ratings DROP CONSTRAINT FKd03estm381c26jhsq4wd44vwx;
ALTER TABLE rbc_evaluation DROP CONSTRAINT FKem9md18gcni93xqa5ijykty8e;
ALTER TABLE rbc_rubric_criterions DROP CONSTRAINT FKilhg1u02m1765ltp3253wp7hn;
ALTER TABLE rbc_rubric_criterions DROP CONSTRAINT FKt5dmnek3q7syuqck0uk9rw2hg;
ALTER TABLE rbc_criterion_ratings DROP KEY UK_funjjd0xkrmm5x300r7i4la83;

ALTER TABLE rbc_criterion DROP COLUMN created;
ALTER TABLE rbc_rating DROP COLUMN created;
ALTER TABLE rbc_criterion DROP COLUMN creatorId;
ALTER TABLE rbc_rating DROP COLUMN creatorId;
ALTER TABLE rbc_rubric DROP COLUMN description;
ALTER TABLE rbc_criterion DROP COLUMN modified;
ALTER TABLE rbc_rating DROP COLUMN modified;
ALTER TABLE rbc_rating DROP COLUMN ownerId;
ALTER TABLE rbc_criterion DROP COLUMN ownerType;
ALTER TABLE rbc_evaluation DROP COLUMN ownerType;
ALTER TABLE rbc_rating DROP COLUMN ownerType;
ALTER TABLE rbc_rubric DROP COLUMN ownerType;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN ownerType;
ALTER TABLE rbc_criterion DROP COLUMN shared;
ALTER TABLE rbc_evaluation DROP COLUMN shared;
ALTER TABLE rbc_rating DROP COLUMN shared;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN shared;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN ownerId;
ALTER TABLE rbc_criterion_outcome MODIFY pointsAdjusted NUMBER(1,0) DEFAULT 0 NULL;
ALTER TABLE rbc_returned_criterion_out MODIFY pointsAdjusted NUMBER(1,0) DEFAULT 0 NULL;
ALTER TABLE rbc_rubric MODIFY shared NUMBER(1,0) DEFAULT 0 NULL;
ALTER TABLE rbc_criterion MODIFY weight DEFAULT NULL;
ALTER TABLE rbc_rubric MODIFY weighted NUMBER(1,0) DEFAULT 0 NULL;
DROP INDEX rbc_tool_item_owner;
CREATE INDEX rbc_tool_item_owner ON rbc_tool_item_rbc_assoc (toolId, itemId, siteId);

-- this migrates the data from the link tables
-- OWL: rewritten for Oracle and with knowledge that some columns will just end up dropped later
UPDATE rbc_criterion rc
SET rc.rubric_id = (SELECT rrc.rbc_rubric_id FROM rbc_rubric_criterions rrc WHERE rc.id = rrc.criterions_id)
WHERE rc.rubric_id is NULL
AND EXISTS (SELECT rrc.rbc_rubric_id FROM rbc_rubric_criterions rrc WHERE rc.id = rrc.criterions_id);

UPDATE rbc_criterion rc
SET rc.order_index = (SELECT rrc.order_index FROM rbc_rubric_criterions rrc WHERE rc.id = rrc.criterions_id)
WHERE rc.order_index is NULL
AND EXISTS (SELECT rrc.order_index FROM rbc_rubric_criterions rrc WHERE rc.id = rrc.criterions_id);

UPDATE rbc_rating rc
SET rc.criterion_id = (SELECT rcr.rbc_criterion_id FROM rbc_criterion_ratings rcr WHERE rc.id = rcr.ratings_id)
WHERE rc.criterion_id is NULL
AND EXISTS (SELECT rcr.rbc_criterion_id FROM rbc_criterion_ratings rcr WHERE rc.id = rcr.ratings_id);
-- once the above conversion is run successfully then the following tables can be dropped
-- DROP TABLE rbc_criterion_ratings;
-- DROP TABLE rbc_rubric_criterions;
-- SAK-46178 END

-- SAK-46257 START
ALTER TABLE CONV_POSTS ADD DEPTH NUMBER(2, 0);
ALTER TABLE CONV_TOPIC_STATUS ADD POSTED NUMBER(1,0);
ALTER TABLE CONV_TOPICS ADD DUE_DATE TIMESTAMP DEFAULT NULL;
ALTER TABLE CONV_TOPICS ADD HIDE_DATE TIMESTAMP DEFAULT NULL;
ALTER TABLE CONV_TOPICS ADD LOCK_DATE TIMESTAMP DEFAULT NULL;
ALTER TABLE CONV_TOPICS ADD SHOW_DATE TIMESTAMP DEFAULT NULL;
ALTER TABLE CONV_POSTS ADD HOW_ACTIVE NUMBER(2, 0);
ALTER TABLE CONV_COMMENTS ADD TOPIC_ID VARCHAR2(36) NOT NULL;
ALTER TABLE CONV_POSTS ADD NUMBER_OF_THREAD_REACTIONS NUMBER(8, 0);
ALTER TABLE CONV_POSTS ADD NUMBER_OF_THREAD_REPLIES NUMBER(8, 0);
ALTER TABLE CONV_POSTS ADD PARENT_THREAD_ID VARCHAR2(255) DEFAULT NULL;
ALTER TABLE CONV_TOPICS ADD MUST_POST_BEFORE_VIEWING NUMBER(1,0);

CREATE INDEX conv_topics_site_creator_idx ON CONV_TOPICS (SITE_ID, CREATOR);
CREATE INDEX conv_posts_parent_thread_idx ON CONV_POSTS (PARENT_THREAD_ID);
CREATE INDEX conv_posts_topic_creator_idx ON CONV_POSTS (TOPIC_ID, CREATOR);
CREATE INDEX conv_comments_topic_idx ON CONV_COMMENTS (TOPIC_ID);

ALTER TABLE CONV_COMMENTS DROP CONSTRAINT FK5ivsmxyitqpbm7pmdnu3lnmyi;
ALTER TABLE CONV_POSTS DROP CONSTRAINT FKc21ukywsqsqilxlsdrg4x6qka;
ALTER TABLE CONV_USER_STATISTICS DROP CONSTRAINT FKi9pfkqq0396p0kl718e9mrakk;
ALTER TABLE CONV_POST_REACTION_TOTALS DROP CONSTRAINT FKirwlickqy5sf8o9ejk1qkuit6;
ALTER TABLE CONV_TOPIC_REACTIONS DROP CONSTRAINT FKpwv7vrkag66g9kq6gghtc4uy1;
ALTER TABLE CONV_POSTS DROP CONSTRAINT FKqaspmpv6ull7whideia5i2cnb;
ALTER TABLE CONV_TOPIC_REACTION_TOTALS DROP CONSTRAINT FKqu7eyh63vtkowyqoqa9xy7wmq;
ALTER TABLE CONV_POST_REACTIONS DROP CONSTRAINT FKqv38yghf2km7vq1i717xywih6;
-- SAK-46257 END

-- SAK-47231 START
ALTER TABLE CONV_POST_STATUS MODIFY POST_ID VARCHAR(36);
ALTER TABLE CONV_POST_STATUS MODIFY TOPIC_ID VARCHAR(36);
ALTER TABLE CONV_TOPIC_STATUS MODIFY TOPIC_ID VARCHAR(36);
-- SAK-47231 END

--------------------- End 22.0 -> 22.1 ------------------------------

------------------- Begin 22.1 -> 22.2 ------------------------------

-- Begin SAK-47582
create index TOOL_IDX on lti_content (TOOL_ID);
-- End SAK-47582

-- SAK-47837 start
ALTER TABLE rbc_returned_criterion_out DROP CONSTRAINT FK_RBC_RETURNED_CRITERION_ID;
ALTER TABLE rbc_criterion_outcome DROP CONSTRAINT FKalvarr6g412wt7wto6tutsddu;

ALTER TABLE rbc_rating DROP COLUMN order_index;
ALTER TABLE rbc_criterion DROP COLUMN ownerId;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN siteId;
-- OWL: we can't just not null this column because we still have nulls after running the migration script earlier
-- and we can't just drop a default in Oracle, so we have to do the copy column shuffle
-- ALTER TABLE rbc_rating MODIFY criterion_id BIGINT NOT NULL;
-- ALTER TABLE rbc_rating ALTER criterion_id DROP DEFAULT;
ALTER TABLE rbc_rating ADD criterion_id2 NUMBER (19,0);
UPDATE rbc_rating SET criterion_id2 = criterion_id;
ALTER TABLE rbc_rating DROP COLUMN criterion_id;
ALTER TABLE rbc_rating RENAME COLUMN criterion_id2 TO criterion_id;
DELETE FROM rbc_rating WHERE criterion_id IS NULL;
ALTER TABLE rbc_rating MODIFY criterion_id NUMBER(19,0) NOT NULL;
CREATE INDEX FK_n44rjf77gscr2kqkamfbpkc7t ON rbc_rating(criterion_id);
ALTER TABLE rbc_rating ADD CONSTRAINT FK_n44rjf77gscr2kqkamfbpkc7t FOREIGN KEY (criterion_id) REFERENCES rbc_criterion (id);

-- OWL: same as above Oracle makes this complicated
-- ALTER TABLE rbc_tool_item_rbc_assoc MODIFY rubric_id BIGINT NOT NULL;
-- ALTER TABLE rbc_tool_item_rbc_assoc ALTER rubric_id DROP DEFAULT;
ALTER TABLE rbc_tool_item_rbc_assoc ADD rubric_id2 NUMBER(19,0);
UPDATE rbc_tool_item_rbc_assoc SET rubric_id2 = rubric_id;
ALTER TABLE rbc_tool_item_rbc_assoc DROP CONSTRAINT rbc_item_rubric;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN rubric_id;
ALTER TABLE rbc_tool_item_rbc_assoc RENAME COLUMN rubric_id2 TO rubric_id;
DELETE FROM rbc_tool_item_rbc_assoc WHERE rubric_id IS NULL;
ALTER TABLE rbc_tool_item_rbc_assoc MODIFY rubric_id NUMBER(19,0) NOT NULL;
CREATE INDEX FK_6dwej9j9vx5viukv8w86chbbc ON rbc_tool_item_rbc_assoc(rubric_id);
ALTER TABLE rbc_tool_item_rbc_assoc ADD CONSTRAINT FK_6dwej9j9vx5viukv8w86chbbc FOREIGN KEY (rubric_id) REFERENCES rbc_rubric (id) ;
ALTER TABLE rbc_tool_item_rbc_assoc ADD CONSTRAINT rbc_item_rubric UNIQUE (itemId, rubric_id);

CREATE INDEX rbc_tool_item ON rbc_tool_item_rbc_assoc(toolId, itemId);
DROP INDEX rbc_tool_item_owner;
-- SAK-47837 end

-------------------- End 22.1 -> 22.2 -------------------------------

-------- Missed snippet that should have been in 22.0 -> 22.1 -------

-- SAK-47291
UPDATE gb_gradable_object_t SET EXTERNAL_APP_NAME = 'sakai.assignment.grades' WHERE EXTERNAL_ID LIKE '/assignment/a/%';
UPDATE gb_gradable_object_t SET EXTERNAL_APP_NAME = 'sakai.lessonbuildertool' WHERE EXTERNAL_ID LIKE 'lesson-builder:%';
UPDATE gb_gradable_object_t SET EXTERNAL_APP_NAME = 'sakai.attendance' WHERE EXTERNAL_ID LIKE 'sakai.attendance.%';
UPDATE gb_gradable_object_t SET EXTERNAL_APP_NAME = 'sakai.samigo' WHERE REGEXP_LIKE(EXTERNAL_ID, '^[0-9]+$');
-- END SAK-47291
